"use client";
import { useEffect, useMemo, useState } from "react";

type Tab="기업 데이터"|"OEM&ODM"|"플랫폼·유통";
type Row={id:string;company:string;category:string;revenue2024:number;revenue2025:number;revenue2024Consolidated:number;revenue2025Consolidated:number;brands:string;overseas:string;business:string;keyRoles:string;source:string;updatedAt?:string};
const fallback:Record<Tab,Row[]>={
  "기업 데이터":[
    {id:"amorepacific",company:"아모레퍼시픽",category:"대형 종합 뷰티",revenue2024:321300,revenue2025:340730,revenue2024Consolidated:0,revenue2025Consolidated:0,brands:"설화수, 라네즈, 헤라",overseas:"북미·일본·중국",business:"화장품·뷰티",keyRoles:"글로벌영업, 브랜드마케팅, 상품기획",source:"별도"},
    {id:"lg-hh",company:"LG생활건강",category:"대형 종합 뷰티",revenue2024:210150,revenue2025:216640,revenue2024Consolidated:0,revenue2025Consolidated:0,brands:"더후, CNP, 오휘",overseas:"북미·중국·일본",business:"화장품·생활용품·음료",keyRoles:"글로벌영업, 브랜드마케팅, 상품기획, R&D",source:"별도"},
    {id:"apr",company:"에이피알",category:"성장 인디 브랜드",revenue2024:126250,revenue2025:178860,revenue2024Consolidated:0,revenue2025Consolidated:0,brands:"메디큐브, 에이프릴스킨, 포맨트",overseas:"미국·일본·중국 등",business:"뷰티 디바이스·화장품·패션",keyRoles:"해외영업, 글로벌마케팅, 이커머스",source:"별도"},
    {id:"able-cn",company:"에이블씨엔씨",category:"성장 인디 브랜드",revenue2024:131690,revenue2025:123500,revenue2024Consolidated:0,revenue2025Consolidated:0,brands:"미샤, 어퓨",overseas:"미국·일본·유럽",business:"화장품 브랜드",keyRoles:"해외영업, 브랜드마케팅, 상품기획",source:"별도"},
    {id:"vt",company:"브이티",category:"성장 인디 브랜드",revenue2024:7911,revenue2025:9018,revenue2024Consolidated:0,revenue2025Consolidated:0,brands:"VT, 리들샷",overseas:"일본·미국·유럽",business:"화장품·글로벌 뷰티",keyRoles:"해외영업, 글로벌마케팅, 브랜드마케팅",source:"별도"},
    {id:"goodai",company:"구다이글로벌",category:"성장 인디 브랜드",revenue2024:3237,revenue2025:4565,revenue2024Consolidated:0,revenue2025Consolidated:0,brands:"조선미녀, 스킨1004, 티르티르",overseas:"북미·일본·유럽·동남아",business:"글로벌 뷰티 브랜드 빌더·유통·M&A",keyRoles:"글로벌영업, 브랜드PM, 유통, 마케팅",source:"별도"},
    {id:"dalba",company:"달바글로벌",category:"성장 인디 브랜드",revenue2024:30302,revenue2025:50259,revenue2024Consolidated:0,revenue2025Consolidated:0,brands:"달바",overseas:"미국·일본·유럽",business:"프리미엄 뷰티 브랜드",keyRoles:"글로벌영업, 브랜드마케팅, 이커머스",source:"별도"}
  ],
  "OEM&ODM":[
    {id:"cosmax",company:"코스맥스",category:"OEM&ODM",revenue2024:17683,revenue2025:18892,revenue2024Consolidated:0,revenue2025Consolidated:0,brands:"글로벌 ODM",overseas:"미국·중국·동남아",business:"화장품 ODM",keyRoles:"생산기획, 해외영업, R&D, 품질, SCM",source:"별도"},
    {id:"kolmar",company:"한국콜마",category:"OEM&ODM",revenue2024:6169,revenue2025:7736,revenue2024Consolidated:0,revenue2025Consolidated:0,brands:"글로벌 ODM",overseas:"미국·중국·북미",business:"화장품·건강기능식품 ODM",keyRoles:"R&D, 생산, 품질, 해외영업, SCM",source:"별도"}
  ],
  "플랫폼·유통":[
    {id:"oliveyoung",company:"올리브영",category:"플랫폼·유통",revenue2024:478990,revenue2025:583350,revenue2024Consolidated:0,revenue2025Consolidated:0,brands:"K-뷰티 유통 플랫폼",overseas:"글로벌 온라인·오프라인",business:"H&B 리테일·온라인 플랫폼",keyRoles:"MD, 글로벌사업, 이커머스, 마케팅, 데이터",source:"공시/공개자료"}
  ]
};
const money=(v:number)=>v>=10000?`${Math.floor(v/10000)}조${v%10000?`${Math.round(v%10000).toLocaleString("ko-KR")}억`:""}`:`${Math.round(v).toLocaleString("ko-KR")}억`;
const growth=(r:Row)=>r.revenue2024?((r.revenue2025-r.revenue2024)/r.revenue2024*100):0;
function normalize(c:any):Row{return {id:String(c.id),company:c.company,category:c.category,revenue2024:Number(c.revenue_2024)||0,revenue2025:Number(c.revenue_2025)||0,revenue2024Consolidated:Number(c.revenue_2024_consolidated)||0,revenue2025Consolidated:Number(c.revenue_2025_consolidated)||0,brands:c.brands||"",overseas:c.location||"",business:c.items||c.odm||"",keyRoles:c.memo||"",source:"DB",updatedAt:c.updated_at};}
function slug(name:string){return name.toLowerCase().replace(/[^a-z0-9가-힣]+/g,"-").replace(/^-|-$/g,"")||`company-${Date.now()}`;}
export default function CompanyData(){
  const [tab,setTab]=useState<Tab>("기업 데이터");
  const [q,setQ]=useState("");
  const [rows,setRows]=useState<Record<Tab,Row[]>>(fallback);
  const [editing,setEditing]=useState<Row|null>(null);
  const [year,setYear]=useState("2025");
  const [revenue,setRevenue]=useState("");
  const [source,setSource]=useState("직접 입력");
  const [sourceUrl,setSourceUrl]=useState("");
  const [saving,setSaving]=useState(false);
  const [message,setMessage]=useState("");
  useEffect(()=>{(async()=>{try{const r=await fetch("/api/companies",{cache:"no-store"});const d=await r.json();if(d.ok&&Array.isArray(d.companies)&&d.companies.length){const grouped:{[key:string]:Row[]}={};for(const c of d.companies){const row=normalize(c);const key=(Object.keys(fallback) as Tab[]).includes(row.category as Tab)?row.category as Tab:(row.category==="OEM&ODM"?"OEM&ODM":row.category==="플랫폼·유통"?"플랫폼·유통":"기업 데이터");(grouped[key] ||= []).push(row);}setRows({...fallback,...grouped} as Record<Tab,Row[]>);}}catch{}})();},[]);
  const data=useMemo(()=>rows[tab].filter(r=>`${r.company} ${r.category} ${r.brands} ${r.overseas} ${r.business}`.toLowerCase().includes(q.toLowerCase())),[rows,tab,q]);
  const total=data.reduce((s,r)=>s+r.revenue2025,0);
  function openEdit(r:Row){setEditing(r);setYear("2025");setRevenue(String(r.revenue2025));setSource(r.source==="DB"?"직접 입력":r.source);setSourceUrl("");setMessage("");}
  async function save(){if(!editing)return;const n=Number(revenue.replace(/,/g,""));if(!Number.isFinite(n)||n<0){setMessage("매출은 숫자로 입력해 주세요.");return;}setSaving(true);setMessage("");try{
      const id=editing.id||slug(editing.company);
      const company={id,company:editing.company,category:editing.category,revenue2024:editing.revenue2024,revenue2025:editing.revenue2025,revenue2024Consolidated:editing.revenue2024Consolidated,revenue2025Consolidated:editing.revenue2025Consolidated,brands:editing.brands,location:editing.overseas,items:editing.business,memo:editing.keyRoles};
      const financial=await fetch("/api/financials",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({companyId:id,fiscalYear:Number(year),separateRevenue:n,source:source||"직접 입력",sourceUrl})});
      if(financial.ok){const updated={...editing,id,...(Number(year)===2025?{revenue2025:n}:{revenue2024:n}),source:source||"직접 입력",updatedAt:new Date().toISOString()};setRows(prev=>({...prev,[tab]:prev[tab].map(x=>x.id===editing.id?updated:x)}));setEditing(null);setMessage("매출이 저장되었습니다. OpenAI API를 사용하지 않는 수동 업데이트입니다.");}
      else {const d=await financial.json();if(d.error?.includes("POSTGRES_URL")){setMessage("DB가 연결되지 않았습니다. 현재 배포 환경의 POSTGRES_URL을 확인해 주세요.");}else if(d.error?.includes("관리자")){setMessage("관리자 로그인 후 수정할 수 있습니다.");}else setMessage(d.error||"저장에 실패했습니다.");}
    }catch{setMessage("저장 중 오류가 발생했습니다.");}finally{setSaving(false);}}
  return <main className="page"><style>{`.wrap{padding:18px 14px 30px}.head{display:flex;justify-content:space-between;align-items:flex-end;margin-bottom:16px}.ey{font-size:10px;font-weight:800;letter-spacing:.12em;color:#718099}.head h1{font-size:28px;margin:4px 0}.head p{font-size:11px;color:#758198}.tabs{display:flex;gap:7px;margin-bottom:12px}.tab{border:1px solid #dce2eb;background:#fff;border-radius:8px;padding:10px 16px;font-size:11px;font-weight:800;cursor:pointer;color:#42516a}.tab.on{background:#172844;color:#fff;border-color:#172844}.card{background:#fff;border:1px solid #e2e7ef;border-radius:10px;box-shadow:0 3px 13px rgba(20,35,60,.04);padding:14px}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:12px}.stat span{font-size:10px;color:#7a8496;display:block;margin-bottom:6px}.stat b{font-size:20px}.tablehead{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}.tablehead h2{font-size:14px;margin:0}.tablehead span{font-size:10px;color:#7a8496}table{width:100%;border-collapse:collapse;min-width:1050px}th,td{text-align:left;border-bottom:1px solid #edf0f4;padding:9px 7px;font-size:10px;vertical-align:top}th{font-size:9px;color:#7b8494;background:#fafbfd}td b{font-size:11px}.up{color:#ef4444;font-weight:800}.down{color:#2563eb;font-weight:800}.tag{display:inline-block;padding:4px 7px;border-radius:999px;background:#eef2f7;color:#516074;font-size:9px;font-weight:700}.btn{border:1px solid #d8dee8;background:#fff;border-radius:7px;padding:6px 9px;font-size:9px;font-weight:800;cursor:pointer}.btn.dark{background:#172844;color:#fff;border-color:#172844}.note{margin-top:10px;color:#8992a2;font-size:9px}.modalbg{position:fixed;inset:0;background:rgba(15,25,40,.45);display:flex;align-items:center;justify-content:center;padding:20px;z-index:50}.modal{width:min(520px,100%);background:#fff;border-radius:12px;padding:20px;box-shadow:0 20px 60px rgba(0,0,0,.2)}.modal h2{margin:0 0 4px;font-size:17px}.modal p{font-size:10px;color:#778197;margin:0 0 15px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.field label{display:block;font-size:10px;font-weight:800;margin-bottom:5px}.field input{width:100%;box-sizing:border-box;padding:9px;border:1px solid #dce2eb;border-radius:7px;font-size:11px}.actions{display:flex;justify-content:flex-end;gap:7px;margin-top:15px}.msg{margin-top:10px;font-size:10px;color:#516074}@media(max-width:800px){.summary{grid-template-columns:1fr}.head{align-items:flex-start;flex-direction:column;gap:10px}.tabs{overflow:auto}.tab{white-space:nowrap}.grid{grid-template-columns:1fr}}`}</style><div className="wrap">
    <header className="head"><div><div className="ey">2025 K-BEAUTY INDUSTRY LANDSCAPE</div><h1>기업 데이터</h1><p>기업 매출은 자동으로 바뀌지 않으며, 관리자가 필요할 때 직접 업데이트합니다.</p></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="기업명 검색..." style={{padding:"9px 11px",border:"1px solid #dce2eb",borderRadius:7,fontSize:11,width:180}}/></header>
    <div className="tabs">{(Object.keys(rows) as Tab[]).map(t=><button key={t} className={`tab ${tab===t?"on":""}`} onClick={()=>setTab(t)}>{t}</button>)}</div>
    <section className="summary"><div className="card stat"><span>현재 구분</span><b>{tab}</b></div><div className="card stat"><span>기업 수</span><b>{data.length}개</b></div><div className="card stat"><span>2025 매출 합계</span><b>{money(total)}</b></div></section>
    <section className="card"><div className="tablehead"><div><h2>{tab} 기업 데이터</h2><span>자동 업데이트 없음 · 필요할 때 「수동 수정」으로 변경</span></div><span>총 {data.length}개</span></div><div style={{overflowX:"auto"}}><table><thead><tr><th>기업명</th><th>카테고리</th><th>2024 매출</th><th>2025 매출</th><th>전년 대비</th><th>매출 기준</th><th>주요 브랜드</th><th>해외 시장</th><th>주요 사업</th><th>주요 채용 직무</th><th>관리</th></tr></thead><tbody>{data.map(r=>{const g=growth(r);return <tr key={r.id}><td><b>{r.company}</b></td><td>{r.category}</td><td>{money(r.revenue2024)}</td><td><b>{money(r.revenue2025)}</b></td><td className={g>=0?"up":"down"}>{g>=0?"+":""}{g.toFixed(2)}%</td><td><span className="tag">{r.source}</span></td><td>{r.brands}</td><td>{r.overseas}</td><td>{r.business}</td><td>{r.keyRoles}</td><td><button className="btn" onClick={()=>openEdit(r)}>수동 수정</button></td></tr>})}</tbody></table></div><p className="note">※ 「수동 수정」은 OpenAI API를 호출하지 않습니다. 매출 숫자와 출처를 직접 확인한 뒤 저장하는 방식입니다. 자동 스케줄/자동 덮어쓰기는 설정하지 않았습니다.</p></section>
    {message&&<p className="msg">{message}</p>}
  </div>
  {editing&&<div className="modalbg" onMouseDown={e=>{if(e.target===e.currentTarget)setEditing(null)}}><div className="modal"><h2>{editing.company} · 매출 수동 업데이트</h2><p>관리자가 확인한 공시/별도매출을 직접 입력합니다. 저장 시 해당 연도의 기업 데이터도 함께 갱신됩니다.</p><div className="grid"><div className="field"><label>회계연도</label><select value={year} onChange={e=>setYear(e.target.value)} style={{width:"100%",padding:"9px",border:"1px solid #dce2eb",borderRadius:7,fontSize:11}}><option>2025</option><option>2024</option><option>2023</option></select></div><div className="field"><label>별도매출 (억원)</label><input value={revenue} onChange={e=>setRevenue(e.target.value)} placeholder="예: 9018"/></div><div className="field"><label>출처</label><input value={source} onChange={e=>setSource(e.target.value)} placeholder="예: 2025 사업보고서"/></div><div className="field"><label>출처 URL (선택)</label><input value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} placeholder="https://..."/></div></div><div className="actions"><button className="btn" onClick={()=>setEditing(null)}>취소</button><button className="btn dark" onClick={save} disabled={saving}>{saving?"저장 중...":"저장"}</button></div></div></div>}
  </main>
}
