"use client";
import {useMemo,useState} from "react";

type Tab="기업 데이터"|"OEM&ODM"|"플랫폼·유통";
type Row={company:string;category:string;revenue2024:number;revenue2025:number;brands:string;overseas:string;business:string;keyRoles:string;source:string};
const rows:Record<Tab,Row[]>={
"기업 데이터":[
{company:"아모레퍼시픽",category:"대형 종합 뷰티",revenue2024:321300,revenue2025:340730,brands:"설화수, 라네즈, 헤라",overseas:"북미·일본·중국",business:"화장품·뷰티",keyRoles:"글로벌영업, 브랜드마케팅, 상품기획",source:"별도"},
{company:"LG생활건강",category:"대형 종합 뷰티",revenue2024:210150,revenue2025:216640,brands:"더후, CNP, 오휘",overseas:"북미·중국·일본",business:"화장품·생활용품·음료",keyRoles:"글로벌영업, 브랜드마케팅, 상품기획, R&D",source:"별도"},
{company:"에이피알",category:"성장 인디 브랜드",revenue2024:126250,revenue2025:178860,brands:"메디큐브, 에이프릴스킨, 포맨트",overseas:"미국·일본·중국 등",business:"뷰티 디바이스·화장품·패션",keyRoles:"해외영업, 글로벌마케팅, 이커머스",source:"별도"},
{company:"에이블씨엔씨",category:"성장 인디 브랜드",revenue2024:131690,revenue2025:123500,brands:"미샤, 어퓨",overseas:"미국·일본·유럽",business:"화장품 브랜드",keyRoles:"해외영업, 브랜드마케팅, 상품기획",source:"별도"},
{company:"브이티",category:"성장 인디 브랜드",revenue2024:7911,revenue2025:9018,brands:"VT, 리들샷",overseas:"일본·미국·유럽",business:"화장품·글로벌 뷰티",keyRoles:"해외영업, 글로벌마케팅, 브랜드마케팅",source:"별도"},
{company:"구다이글로벌",category:"성장 인디 브랜드",revenue2024:3237,revenue2025:4565,brands:"조선미녀, 스킨1004, 티르티르",overseas:"북미·일본·유럽·동남아",business:"글로벌 뷰티 브랜드 빌더·유통·M&A",keyRoles:"글로벌영업, 브랜드PM, 유통, 마케팅",source:"별도"},
{company:"달바글로벌",category:"성장 인디 브랜드",revenue2024:30302,revenue2025:50259,brands:"달바",overseas:"미국·일본·유럽",business:"프리미엄 뷰티 브랜드",keyRoles:"글로벌영업, 브랜드마케팅, 이커머스",source:"별도"}
],
"OEM&ODM":[
{company:"코스맥스",category:"OEM&ODM",revenue2024:17683,revenue2025:18892,brands:"글로벌 ODM",overseas:"미국·중국·동남아",business:"화장품 ODM",keyRoles:"생산기획, 해외영업, R&D, 품질, SCM",source:"별도"},
{company:"한국콜마",category:"OEM&ODM",revenue2024:6169,revenue2025:7736,brands:"글로벌 ODM",overseas:"미국·중국·북미",business:"화장품·건강기능식품 ODM",keyRoles:"R&D, 생산, 품질, 해외영업, SCM",source:"별도"}
],
"플랫폼·유통":[
{company:"올리브영",category:"플랫폼·유통",revenue2024:478990,revenue2025:583350,brands:"K-뷰티 유통 플랫폼",overseas:"글로벌 온라인·오프라인",business:"H&B 리테일·온라인 플랫폼",keyRoles:"MD, 글로벌사업, 이커머스, 마케팅, 데이터",source:"공시/공개자료"}
]};
const money=(v:number)=>v>=10000?`${Math.floor(v/10000)}조${v%10000?`${Math.round(v%10000)}억`:""}`:`${Math.round(v).toLocaleString("ko-KR")}억`;
const growth=(r:Row)=>r.revenue2024?((r.revenue2025-r.revenue2024)/r.revenue2024*100):0;
const css=`.wrap{padding:18px 14px 30px}.head{display:flex;justify-content:space-between;align-items:flex-end;margin-bottom:16px}.ey{font-size:10px;font-weight:800;letter-spacing:.12em;color:#718099}.head h1{font-size:28px;margin:4px 0}.head p{font-size:11px;color:#758198}.tabs{display:flex;gap:7px;margin-bottom:12px}.tab{border:1px solid #dce2eb;background:#fff;border-radius:8px;padding:10px 16px;font-size:11px;font-weight:800;cursor:pointer;color:#42516a}.tab.on{background:#172844;color:#fff;border-color:#172844}.card{background:#fff;border:1px solid #e2e7ef;border-radius:10px;box-shadow:0 3px 13px rgba(20,35,60,.04);padding:14px}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:12px}.stat span{font-size:10px;color:#7a8496;display:block;margin-bottom:6px}.stat b{font-size:20px}.tablehead{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}.tablehead h2{font-size:14px;margin:0}.tablehead span{font-size:10px;color:#7a8496}table{width:100%;border-collapse:collapse;min-width:950px}th,td{text-align:left;border-bottom:1px solid #edf0f4;padding:9px 7px;font-size:10px;vertical-align:top}th{font-size:9px;color:#7b8494;background:#fafbfd}td b{font-size:11px}.up{color:#ef4444;font-weight:800}.down{color:#2563eb;font-weight:800}.tag{display:inline-block;padding:4px 7px;border-radius:999px;background:#eef2f7;color:#516074;font-size:9px;font-weight:700}.note{margin-top:10px;color:#8992a2;font-size:9px}@media(max-width:800px){.summary{grid-template-columns:1fr}.head{align-items:flex-start;flex-direction:column;gap:10px}.tabs{overflow:auto}.tab{white-space:nowrap}}
`;
export default function CompanyData(){const[tab,setTab]=useState<Tab>("기업 데이터");const[q,setQ]=useState("");const data=useMemo(()=>rows[tab].filter(r=>`${r.company} ${r.category} ${r.brands} ${r.overseas} ${r.business}`.toLowerCase().includes(q.toLowerCase())),[tab,q]);const total=data.reduce((s,r)=>s+r.revenue2025,0);return <main className="page"><style>{css}</style><div className="wrap"><header className="head"><div><div className="ey">2025 K-BEAUTY INDUSTRY LANDSCAPE</div><h1>기업 데이터</h1><p>기업군별로 분리한 K-뷰티 기업 데이터베이스</p></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="기업명 검색..." style={{padding:"9px 11px",border:"1px solid #dce2eb",borderRadius:7,fontSize:11,width:180}}/></header><div className="tabs">{(Object.keys(rows) as Tab[]).map(t=><button key={t} className={`tab ${tab===t?"on":""}`} onClick={()=>setTab(t)}>{t}</button>)}</div><section className="summary"><div className="card stat"><span>현재 구분</span><b>{tab}</b></div><div className="card stat"><span>기업 수</span><b>{data.length}개</b></div><div className="card stat"><span>2025 매출 합계</span><b>{money(total)}</b></div></section><section className="card"><div className="tablehead"><div><h2>{tab} 기업 데이터</h2><span>2024/2025 매출은 기존 대시보드 데이터 기준</span></div><span>총 {data.length}개</span></div><div style={{overflowX:"auto"}}><table><thead><tr><th>기업명</th><th>카테고리</th><th>2024 매출</th><th>2025 매출</th><th>전년 대비</th><th>매출 기준</th><th>주요 브랜드</th><th>해외 시장</th><th>주요 사업</th><th>주요 채용 직무</th></tr></thead><tbody>{data.map(r=>{const g=growth(r);return <tr key={r.company}><td><b>{r.company}</b></td><td>{r.category}</td><td>{money(r.revenue2024)}</td><td><b>{money(r.revenue2025)}</b></td><td className={g>=0?"up":"down"}>{g>=0?"+":""}{g.toFixed(2)}%</td><td><span className="tag">{r.source}</span></td><td>{r.brands}</td><td>{r.overseas}</td><td>{r.business}</td><td>{r.keyRoles}</td></tr>})}</tbody></table></div><p className="note">※ 기업 데이터는 현재 산업 지형도에 입력된 데이터를 기준으로 구분했습니다. 별도매출·공개자료 여부는 기존 데이터 기준입니다.</p></section></div></main>}
