"use client";
import {useMemo,useState} from "react";

type Company={name:string;roles:string[];markets:string[];keywords:string[];point:string};
const companies:Company[]=[
{name:"브이티",roles:["해외영업","글로벌마케팅","브랜드마케팅","상품기획"],markets:["미국","유럽","일본"],keywords:["화장품","해외영업","글로벌","OEM","ODM"],point:"미주·유럽 해외영업 경험을 화장품 산업 경험과 연결하기 좋은 기업"},
{name:"에이피알",roles:["해외영업","글로벌마케팅","이커머스","상품기획"],markets:["미국","일본","유럽","중국"],keywords:["화장품","해외영업","D2C","글로벌","이커머스"],point:"글로벌 D2C와 해외사업 확장 경험을 가진 후보자에게 적합"},
{name:"달바글로벌",roles:["해외영업","글로벌마케팅","이커머스","상품기획"],markets:["미국","일본","유럽"],keywords:["화장품","프리미엄","해외영업","이커머스"],point:"프리미엄 뷰티의 해외 B2B·이커머스 경험과 연결"},
{name:"구다이글로벌",roles:["글로벌영업","브랜드PM","유통","마케팅"],markets:["미국","일본","유럽","동남아"],keywords:["글로벌","브랜드","해외영업","유통","마케팅"],point:"멀티브랜드 글로벌 유통과 해외영업 경험을 활용하기 좋음"},
{name:"코스맥스",roles:["해외영업","생산기획","R&D","품질","SCM"],markets:["미국","중국","동남아"],keywords:["OEM","ODM","해외영업","SCM","품질"],point:"화장품 OEM/ODM과 해외 고객 대응 경험을 활용 가능"},
{name:"한국콜마",roles:["해외영업","R&D","생산","품질","SCM"],markets:["미국","중국","북미"],keywords:["OEM","ODM","해외영업","SCM","품질"],point:"OEM/ODM 해외영업 및 고객 대응 경험과 연결 가능"}
];
const sample=`해외영업 경력 3년 이상. 유럽/CIS/아시아/중동 15개국 이상 담당. 약 30개 바이어·디스트리뷰터 관리. LinkedIn을 통한 신규 바이어 발굴 및 동남아 독점 유통계약 경험. 미국 UCSD International Business 전공. 최근 화장품 OEM/ODM 해외영업에서 견적, 수주, 납기, 샘플, 규제지원, 수출입 업무를 수행. 미국 Fenty Beauty, TJMAX 및 인디 브랜드 관련 업무 경험.`;
function score(text:string,c:Company){const t=text.toLowerCase();let s=35;const role=c.roles.some(x=>t.includes(x.toLowerCase().replace("글로벌","")))?18:0;const market=c.markets.some(x=>t.includes(x.toLowerCase()))?12:0;const kw=c.keywords.filter(x=>t.includes(x.toLowerCase())).length;const cosmetic=(t.includes("화장품")||t.includes("beauty"))?15:0;return Math.min(98,s+role+market+Math.min(kw*4,12)+cosmetic)}
export default function Page(){const[text,setText]=useState("");const[ran,setRan]=useState(false);const result=useMemo(()=>companies.map(c=>({c,s:score(text,c)})).sort((a,b)=>b.s-a.s),[text]);const top=result[0];return <main className="page"><header className="hero"><div><div className="eyebrow">RECRUITER WORKSPACE · RESUME MATCH</div><h1>이력서 → K-뷰티 기업 추천</h1><p>후보자의 이력서를 붙여 넣으면 적합 기업, 추천 근거, 보완점, 인재추천 문안을 한 번에 정리합니다.</p></div></header><section className="panel"><h2>① 후보자 이력서 입력</h2><p className="sub">연락처·주소·주민번호 등 개인정보는 넣지 마세요. 경력·직무·산업·시장 경험 중심으로 입력합니다.</p><textarea className="resumeBox" placeholder="이력서의 경력요약과 주요 경력을 붙여 넣으세요." value={text} onChange={e=>{setText(e.target.value);setRan(false)}}/><div className="row"><button className="btn dark" onClick={()=>{setText(sample);setRan(false)}}>샘플 후보자 입력</button><button className="btn light" onClick={()=>setRan(true)} disabled={!text.trim()}>기업 추천 분석</button></div></section>{ran&&<><section className="cards"><div className="card"><span>최우선 추천</span><b>{top.c.name}</b></div><div className="card"><span>최우선 적합도</span><b>{top.s}%</b></div><div className="card"><span>비교 기업</span><b>{companies.length}<small>개</small></b></div><div className="card"><span>분석 방식</span><b>규칙 기반</b></div></section><section className="panel"><h2>② 추천 기업 순위</h2><div className="matchlist">{result.map((r,i)=><button className="matchrow" key={r.c.name} onClick={()=>navigator.clipboard?.writeText(`${r.c.name} ${r.s}%`)}><b>{i+1}</b><span><strong>{r.c.name}</strong><small>{r.c.roles.join(" · ")}</small></span><strong>{r.s}%</strong></button>)}</div></section><section className="analysis-grid"><div className="panel"><h2>③ 1순위 추천 분석</h2><h3>{top.c.name} · {top.s}%</h3><p>{top.c.point}</p><h4>추천 근거</h4><ul><li>해외영업·글로벌 업무 경험과 직무 연관성</li><li>미국·유럽·일본 등 글로벌 시장 경험</li><li>화장품/OEM/ODM 경험이 확인되는 경우 가점</li></ul><h4>확인할 부분</h4><ul><li>화장품 해외영업의 실제 매출·거래처 성과</li><li>미주/유럽 시장에서 직접 계약·채널 운영 경험</li><li>영어 비즈니스 커뮤니케이션 수준</li></ul></div><div className="panel"><h2>④ 헤드헌터 추천 문안</h2><div className="letter">안녕하세요.<br/><br/>[후보자명] 후보자를 {top.c.name}의 글로벌/해외영업 포지션에 추천드립니다.<br/><br/>해외영업 및 글로벌 바이어·디스트리뷰터 관리 경험을 보유하고 있으며, 미국·유럽 등 해외시장 경험과 최근 화장품 OEM/ODM 업무 경험을 함께 갖춘 점이 강점입니다.<br/><br/>특히 해외 거래처 발굴, 신규 채널 개발, 견적·수주·납기·샘플·수출입 등 실무 전반을 경험했다면 해당 포지션과의 연계성이 높습니다.<br/><br/>면접에서는 실제 신규 거래처 발굴 실적과 미주·유럽 매출 기여도를 중심으로 확인을 권합니다.</div><button className="btn light" onClick={()=>navigator.clipboard?.writeText(`안녕하세요.\n\n[후보자명] 후보자를 ${top.c.name}의 글로벌/해외영업 포지션에 추천드립니다.\n\n해외영업 및 글로벌 바이어·디스트리뷰터 관리 경험을 보유하고 있으며, 미국·유럽 등 해외시장 경험과 최근 화장품 OEM/ODM 업무 경험을 함께 갖춘 점이 강점입니다.`)}>추천문안 복사</button></div></section></>}{!ran&&<section className="panel"><h2>이 기능의 사용 순서</h2><div className="steps"><div><b>1</b>이력서 붙여넣기</div><div><b>2</b>기업 추천 분석</div><div><b>3</b>추천 순위 확인</div><div><b>4</b>추천 문안 복사</div></div><p className="sub">현재 버전은 외부 AI API를 호출하지 않는 규칙 기반 1차 매칭입니다. 실제 AI 분석은 API 키를 안전하게 서버 측에 연결한 다음 추가할 수 있습니다.</p></section>}<footer>2026 K-뷰티 헤드헌팅 플랫폼 · Resume Match</footer></main>}
