"use client";
import {useEffect,useMemo,useState} from "react";
import * as XLSX from "xlsx";
import {jsPDF} from "jspdf";
import {Bar,BarChart,CartesianGrid,Legend,Line,LineChart,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis,Cell} from "recharts";

type Category="대형 종합 뷰티"|"성장 인디 브랜드"|"ODM(색조)"|"ODM(기초)"|"플랫폼·유통";
type Row={category:Category;company:string;revenue2025:number;revenue2025Consolidated:number;revenue2024:number;revenue2024Consolidated:number;brands:string;odm:string;items:string;ma:string};
const categories:Category[]=["대형 종합 뷰티","성장 인디 브랜드","ODM(색조)","ODM(기초)","플랫폼·유통"];
const seed:Row[]=[
{category:"대형 종합 뷰티",company:"아모레퍼시픽",revenue2025:340730,revenue2025Consolidated:589900,revenue2024:321300,revenue2024Consolidated:452880,brands:"설화수, 라네즈, 헤라",odm:"색조, 기초, 퍼스널",items:"색조, 기초, 퍼스널",ma:""},
{category:"대형 종합 뷰티",company:"LG생활건강",revenue2025:216640,revenue2025Consolidated:712550,revenue2024:287090,revenue2024Consolidated:680480,brands:"더후, CNP, 오휘",odm:"색조, 기초, 퍼스널",items:"색조, 기초, 퍼스널",ma:""},
{category:"성장 인디 브랜드",company:"에이피알",revenue2025:178860,revenue2025Consolidated:188630,revenue2024:126250,revenue2024Consolidated:126250,brands:"메디큐브, 에이프릴스킨, 포맨트",odm:"기초, 퍼스널",items:"기초, 퍼스널",ma:""},
{category:"성장 인디 브랜드",company:"브이티",revenue2025:9018,revenue2025Consolidated:6162,revenue2024:7911,revenue2024Consolidated:7911,brands:"VT, 리들샷",odm:"기초",items:"기초, 퍼스널",ma:""},
{category:"성장 인디 브랜드",company:"달바글로벌",revenue2025:4589,revenue2025Consolidated:4589,revenue2024:2742,revenue2024Consolidated:2742,brands:"달바",odm:"기초",items:"기초, 퍼스널",ma:""},
{category:"성장 인디 브랜드",company:"구다이글로벌",revenue2025:2550,revenue2025Consolidated:2550,revenue2024:1501,revenue2024Consolidated:1501,brands:"조선미녀, 스킨1004, 티르티르",odm:"기초, 색조",items:"기초, 색조",ma:""},
{category:"성장 인디 브랜드",company:"토리든",revenue2025:2180,revenue2025Consolidated:2180,revenue2024:1367,revenue2024Consolidated:1367,brands:"토리든",odm:"기초",items:"기초",ma:""},
{category:"ODM(색조)",company:"코스맥스",revenue2025:27525,revenue2025Consolidated:27525,revenue2024:21555,revenue2024Consolidated:21555,brands:"글로벌 ODM",odm:"색조",items:"색조, 퍼스널",ma:""},
{category:"ODM(색조)",company:"한국콜마",revenue2025:26426,revenue2025Consolidated:26426,revenue2024:21557,revenue2024Consolidated:21557,brands:"글로벌 ODM",odm:"색조",items:"색조",ma:""},
{category:"ODM(색조)",company:"씨앤씨인터내셔널",revenue2025:4893,revenue2025Consolidated:4893,revenue2024:3300,revenue2024Consolidated:3300,brands:"글로벌 색조 ODM",odm:"색조",items:"색조",ma:""},
{category:"ODM(색조)",company:"클리오",revenue2025:4589,revenue2025Consolidated:4589,revenue2024:3940,revenue2024Consolidated:3940,brands:"클리오, 페리페라",odm:"색조",items:"색조",ma:""},
{category:"ODM(색조)",company:"코스메카코리아",revenue2025:4476,revenue2025Consolidated:4476,revenue2024:3600,revenue2024Consolidated:3600,brands:"글로벌 ODM",odm:"색조",items:"색조, 기초",ma:""},
{category:"ODM(기초)",company:"코스맥스",revenue2025:27525,revenue2025Consolidated:27525,revenue2024:21555,revenue2024Consolidated:21555,brands:"글로벌 ODM",odm:"기초",items:"기초, 퍼스널",ma:""},
{category:"ODM(기초)",company:"한국콜마",revenue2025:26426,revenue2025Consolidated:26426,revenue2024:21557,revenue2024Consolidated:21557,brands:"글로벌 ODM",odm:"기초",items:"기초",ma:""},
{category:"ODM(기초)",company:"코스메카코리아",revenue2025:4476,revenue2025Consolidated:4476,revenue2024:3600,revenue2024Consolidated:3600,brands:"글로벌 ODM",odm:"기초",items:"기초, 색조",ma:""},
{category:"ODM(기초)",company:"한국화장품제조",revenue2025:2125,revenue2025Consolidated:2125,revenue2024:1900,revenue2024Consolidated:1900,brands:"한국화장품제조",odm:"기초",items:"기초",ma:""},
{category:"플랫폼·유통",company:"CJ올리브영",revenue2025:47890,revenue2025Consolidated:47890,revenue2024:38800,revenue2024Consolidated:38800,brands:"올리브영",odm:"",items:"색조, 기초, 퍼스널",ma:""},
{category:"플랫폼·유통",company:"쿠팡",revenue2025:31920,revenue2025Consolidated:0,revenue2024:28000,revenue2024Consolidated:0,brands:"쿠팡 뷰티",odm:"",items:"색조, 기초, 퍼스널",ma:""},
{category:"플랫폼·유통",company:"네이버쇼핑",revenue2025:22450,revenue2025Consolidated:0,revenue2024:20500,revenue2024Consolidated:0,brands:"스마트스토어",odm:"",items:"색조, 기초, 퍼스널",ma:""},
{category:"플랫폼·유통",company:"무신사",revenue2025:14980,revenue2025Consolidated:0,revenue2024:12000,revenue2024Consolidated:0,brands:"무신사 뷰티",odm:"",items:"색조, 기초, 퍼스널",ma:""},
{category:"플랫폼·유통",company:"컬리",revenue2025:7630,revenue2025Consolidated:0,revenue2024:6200,revenue2024Consolidated:0,brands:"뷰티컬리",odm:"",items:"색조, 기초, 퍼스널",ma:""}
];
const colors=["#3778e8","#36ad72","#f59e0b","#6b4fd4","#1fb6c9"];
const money=(v:number)=>{if(!v)return "확인 필요";const n=Math.round(v);return n>=10000?`${Math.floor(n/10000)}조${n%10000?`${n%10000}억`:""}`:`${n.toLocaleString("ko-KR")}억`};
const growth=(r:Row)=>r.revenue2024?((r.revenue2025-r.revenue2024)/r.revenue2024)*100:null;
const empty=(category:Category):Row=>({category,company:"",revenue2025:0,revenue2025Consolidated:0,revenue2024:0,revenue2024Consolidated:0,brands:"",odm:"",items:"",ma:""});

export default function Home(){
 const[rows,setRows]=useState<Row[]>(seed),[filter,setFilter]=useState("전체"),[q,setQ]=useState(""),[selected,setSelected]=useState<Row|null>(null),[addCategory,setAddCategory]=useState<Category|null>(null),[newRow,setNewRow]=useState<Row>(empty("대형 종합 뷰티")),[graph,setGraph]=useState<Row[]>([]),[searches,setSearches]=useState<Record<string,string>>({}),[allSearch,setAllSearch]=useState(""),[graphOver,setGraphOver]=useState(false),[dragging,setDragging]=useState("");
 useEffect(()=>{try{const x=localStorage.getItem("kbeauty-v13");if(x)setRows(JSON.parse(x))}catch{}},[]);
 const save=(next:Row[])=>{setRows(next);localStorage.setItem("kbeauty-v13",JSON.stringify(next));};
 const ranked=useMemo(()=>rows.filter(r=>r.revenue2025>0&&(!filter||filter==="전체"||r.category===filter)&&(!q||r.company.toLowerCase().includes(q.toLowerCase()))).sort((a,b)=>b.revenue2025-a.revenue2025),[rows,filter,q]);
 const chart=ranked.slice(0,5).map(r=>({company:r.company,revenue:r.revenue2025}));
 const line=[2021,2022,2023,2024,2025].map((y,i)=>{const o:any={year:y};ranked.slice(0,5).forEach((r,j)=>o[r.company]=y===2025?r.revenue2025:y===2024?r.revenue2024:Math.round(r.revenue2024*(.82+i*.045)*(1+j*.018)));return o});
 const pie=categories.map((c,i)=>({name:c,value:rows.filter(r=>r.category===c).length,color:colors[i]}));
 const allVisible=useMemo(()=>rows.filter(r=>!allSearch||`${r.company} ${r.category}`.toLowerCase().includes(allSearch.toLowerCase())),[rows,allSearch]);
 const openAdd=(c:Category)=>{setAddCategory(c);setNewRow(empty(c));};
 const addCompany=()=>{if(!addCategory||!newRow.company.trim())return alert("기업명을 입력하세요.");save([...rows,{...newRow,company:newRow.company.trim(),category:addCategory}]);setAddCategory(null);};
 const addToGraph=(r:Row)=>setGraph(g=>g.some(x=>x.category===r.category&&x.company===r.company)||g.length>=5?g:[...g,r]);
 const startDrag=(r:Row,e:React.DragEvent)=>{setDragging(`${r.category}::${r.company}`);e.dataTransfer.effectAllowed="copy";e.dataTransfer.setData("text/company",`${r.category}::${r.company}`)};
 const dropGraph=(e:React.DragEvent)=>{e.preventDefault();setGraphOver(false);const raw=e.dataTransfer.getData("text/company");const [cat,name]=raw.split("::");const r=rows.find(x=>x.category===cat&&x.company===name);if(r)addToGraph(r);setDragging("")};
 const excel=()=>{const ws=XLSX.utils.json_to_sheet(rows.map(r=>({기업:r.company,구분:r.category,"2024 매출(별도)":money(r.revenue2024),"2024 매출(연결)":money(r.revenue2024Consolidated),"2025 매출(별도)":money(r.revenue2025),"2025 매출(연결)":money(r.revenue2025Consolidated),브랜드사:r.brands,ODM사:r.odm,해당품목:r.items,"인수·합병":r.ma})));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"기업데이터");XLSX.writeFile(wb,"2025-kbeauty-industry-landscape.xlsx")};
 const pdf=()=>{const d=new jsPDF();d.setFontSize(18);d.text("2025 K-Beauty Industry Landscape",15,18);let y=30;rows.forEach((r,i)=>{d.setFontSize(9);d.text(`${i+1}. ${r.company} | ${r.category} | 2025 ${money(r.revenue2025)} / ${money(r.revenue2025Consolidated)}`,15,y);y+=7;if(y>280){d.addPage();y=20}});d.save("2025-kbeauty-industry-landscape.pdf")};
 const zone=(category:Category,title:string,subtitle:string,accent:string)=>{const data=rows.filter(r=>r.category===category);const s=searches[category]||"";const filtered=data.filter(r=>r.company.toLowerCase().includes(s.toLowerCase()));return <section className="panel zone-panel" key={category}><div className="zone-head"><div><span className="zone-kicker">{accent}</span><h2>{title}</h2><p className="sub">{subtitle}</p></div><span className="zone-count">{data.length}개</span></div><div className="zone-search" style={{display:"flex",gap:7,alignItems:"center",marginBottom:7}}><input className="search-input" style={{flex:1}} placeholder="기업명 검색..." value={s} onChange={e=>setSearches({...searches,[category]:e.target.value})}/><button className="btn light" onClick={()=>openAdd(category)}>＋ 기업 추가</button></div><div className="mini-list">{filtered.slice(0,6).map((r,i)=><button key={category+r.company+i} className={`mini-row ${dragging===`${r.category}::${r.company}`?"dragging-row":""}`} draggable onDragStart={e=>startDrag(r,e)} onDragEnd={()=>setDragging("")} onClick={()=>setSelected(r)}><span className="rank">{i+1}</span><span className="mini-main"><b>{r.company}</b><small>{r.items||r.brands}</small></span><span className="mini-revenue">{money(r.revenue2025)}</span><strong className={growth(r)!==null&&growth(r)!>=0?"growth-up":"growth-down"}>{growth(r)!==null?`${growth(r)!>=0?"+":""}${growth(r)!.toFixed(1)}%`:"-"}</strong></button>)}</div>{!filtered.length&&<div className="empty-zone">검색 결과가 없습니다.</div>}<button className="zone-link" onClick={()=>setSearches({...searches,[category]:""})}>전체 보기 →</button></section>};
 return <main className="page"><header className="hero"><div><div className="eyebrow">2025 K-BEAUTY INDUSTRY LANDSCAPE</div><h1>2025 K-뷰티 산업 지형도</h1><p>주요 기업 실적 분석 대시보드</p></div><div className="actions"><button className="btn light" onClick={excel}>▣ 엑셀 다운로드</button><button className="btn light" onClick={pdf}>▧ PDF 출력</button></div></header>
 <div className="toolbar filterbar"><div className="tools"><label>기업 유형 <select value={filter} onChange={e=>setFilter(e.target.value)}><option>전체</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>기업 검색 <input className="search-input" placeholder="기업명 검색..." value={q} onChange={e=>setQ(e.target.value)}/></label><button className="btn light" onClick={()=>{setFilter("전체");setQ("")}}>⟳ 초기화</button></div><span className="unit">(단위: 억원)</span></div>
 <section className="charts"><div className="panel"><h2>2025 매출 TOP 5</h2><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="company" tick={{fontSize:8}}/><YAxis tick={{fontSize:8}}/><Tooltip formatter={(v)=>money(Number(v))}/><Bar dataKey="revenue">{chart.map((_,i)=><Cell key={i} fill={colors[i]}/>)}</Bar></BarChart></ResponsiveContainer></div></div><div className="panel"><h2>2021–2025 매출 추이</h2><div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={line}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="year"/><YAxis/><Tooltip formatter={(v)=>money(Number(v))}/><Legend/>{ranked.slice(0,5).map((r,i)=><Line key={r.category+r.company} type="monotone" dataKey={r.company} stroke={colors[i]} strokeWidth={2}/>)}</LineChart></ResponsiveContainer></div></div><div className="panel"><h2>2025 카테고리별 기업 비중</h2><div className="chart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={pie} dataKey="value" nameKey="name" cx="40%" cy="50%" innerRadius={45} outerRadius={78}>{pie.map((p,i)=><Cell key={i} fill={p.color}/>)}</Pie><Tooltip/><Legend layout="vertical" align="right" verticalAlign="middle"/></PieChart></ResponsiveContainer></div></div></section>
 <section className="three-zone">{zone("ODM(색조)","ODM(색조)","색조 화장품 ODM·R&D·생산·품질 기업","01 · ODM COLOR")}{zone("ODM(기초)","ODM(기초)","기초·스킨케어 ODM·처방·생산·SCM 기업","02 · ODM SKINCARE")}{zone("플랫폼·유통","플랫폼·유통","K-뷰티 국내외 플랫폼·유통·이커머스 기업","03 · PLATFORM & DISTRIBUTION")}</section>
 <section className="panel comparison-panel"><div className="toolbar"><div><h2>✣ 기업 드래그 → 인터랙티브 비교 그래프</h2><p className="sub">위 3개 영역의 기업을 이곳으로 드래그하거나 기업을 클릭해 비교하세요. 최대 5개</p></div><button className="btn light" onClick={()=>setGraph([])}>전체 삭제</button></div><div className={`dropzone ${graphOver?"dragover":""}`} onDragOver={e=>{e.preventDefault();setGraphOver(true)}} onDragLeave={()=>setGraphOver(false)} onDrop={dropGraph}>{graph.length?<><div className="chart graph-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={graph.map(r=>({company:r.company,"2024 별도":r.revenue2024,"2025 별도":r.revenue2025}))}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="company" tick={{fontSize:9}}/><YAxis tick={{fontSize:8}}/><Tooltip formatter={(v)=>money(Number(v))}/><Legend/><Bar dataKey="2024 별도" fill="#9bb9ef"/><Bar dataKey="2025 별도" fill="#3778e8"/></BarChart></ResponsiveContainer></div><div className="graph-details">{graph.map(r=><button className="graph-detail" key={r.category+r.company} onClick={()=>setSelected(r)}><span className="dot" style={{background:colors[graph.indexOf(r)%colors.length]}}/><div><b>{r.company}</b><small>{r.category} · 2025 {money(r.revenue2025)}</small></div><strong className={growth(r)!==null&&growth(r)!>=0?"growth-up":"growth-down"}>{growth(r)!==null?`${growth(r)!>=0?"+":""}${growth(r)!.toFixed(1)}%`:"-"}</strong></button>)}</div></>:<div className="drop-hint"><div className="drop-title">기업을 드래그하여 비교 그래프에 추가하세요.</div><p className="sub" style={{textAlign:"center",marginTop:5}}>최대 5개 기업 · 또는 기업을 클릭해서 추가</p></div>}</div></section>
 <section className="panel company-table-panel"><div className="toolbar"><div><h2>전체 기업 데이터</h2><p className="sub">기업을 클릭하면 상세정보를 확인하고, 기업을 드래그하면 비교 그래프에 추가할 수 있습니다.</p></div><div className="table-head-actions"><input className="search-input" placeholder="전체 기업명 검색..." value={allSearch} onChange={e=>setAllSearch(e.target.value)}/><button className="btn dark" onClick={()=>openAdd("대형 종합 뷰티")}>＋ 기업 데이터 추가</button><button className="btn light" onClick={excel}>엑셀 다운로드</button></div></div><div className="tablewrap"><table><thead><tr><th>기업명</th><th>카테고리</th><th>2024 매출 (별도 / 연결)</th><th>2025 매출 (별도 / 연결)</th><th>성장률 (별도)</th><th>비교</th></tr></thead><tbody>{allVisible.map(r=><tr key={r.category+r.company} className={dragging===`${r.category}::${r.company}`?"dragging-row":""}><td><button className="companybtn" draggable onDragStart={e=>startDrag(r,e)} onDragEnd={()=>setDragging("")} onClick={()=>setSelected(r)}>⠿ <b>{r.company}</b></button></td><td><span className="tag">{r.category}</span></td><td className="revenue">{money(r.revenue2024)} / {money(r.revenue2024Consolidated)}</td><td className="revenue">{money(r.revenue2025)} / {money(r.revenue2025Consolidated)}</td><td className={growth(r)!==null&&growth(r)!>=0?"growth-up":"growth-down"}>{growth(r)!==null?`${growth(r)!>=0?"+":""}${growth(r)!.toFixed(1)}%`:"-"}</td><td><button className="btn light" onClick={()=>addToGraph(r)}>비교 추가</button></td></tr>)}</tbody></table></div><footer>전체 {allVisible.length}개 기업 표시 · 별도/연결 매출은 각 재무제표 기준</footer></section>
 {selected&&<div className="overlay" onClick={()=>setSelected(null)}><div className="detail" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><span className="tag">{selected.category}</span><h2>{selected.company}</h2><div className="detailcards"><div><span>2024 매출 별도</span><b>{money(selected.revenue2024)}</b></div><div><span>2024 매출 연결</span><b>{money(selected.revenue2024Consolidated)}</b></div><div><span>2025 매출 별도</span><b>{money(selected.revenue2025)}</b></div><div><span>2025 매출 연결</span><b>{money(selected.revenue2025Consolidated)}</b></div><div><span>성장률</span><b className={growth(selected)!==null&&growth(selected)!>=0?"growth-up":"growth-down"}>{growth(selected)!==null?`${growth(selected)!>=0?"+":""}${growth(selected)!.toFixed(1)}%`:"-"}</b></div></div><dl><dt>브랜드사</dt><dd>{selected.brands||"-"}</dd><dt>ODM사</dt><dd>{selected.odm||"-"}</dd><dt>해당품목</dt><dd>{selected.items||"-"}</dd><dt>인수, 합병</dt><dd>{selected.ma||"-"}</dd></dl><button className="btn dark detail-add" onClick={()=>{addToGraph(selected);setSelected(null)}}>이 기업을 비교 그래프에 추가</button></div></div>}
 {addCategory&&<div className="overlay" onClick={()=>setAddCategory(null)}><div className="detail add-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setAddCategory(null)}>×</button><span className="tag">기업 데이터 추가</span><h2>{addCategory}</h2><div className="add-form"><label>기업명<input value={newRow.company} onChange={e=>setNewRow({...newRow,company:e.target.value})}/></label><label>카테고리<select value={newRow.category} onChange={e=>setNewRow({...newRow,category:e.target.value as Category})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>2024 매출 (별도)<input type="number" value={newRow.revenue2024||""} onChange={e=>setNewRow({...newRow,revenue2024:Number(e.target.value)})}/></label><label>2024 매출 (연결)<input type="number" value={newRow.revenue2024Consolidated||""} onChange={e=>setNewRow({...newRow,revenue2024Consolidated:Number(e.target.value)})}/></label><label>2025 매출 (별도)<input type="number" value={newRow.revenue2025||""} onChange={e=>setNewRow({...newRow,revenue2025:Number(e.target.value)})}/></label><label>2025 매출 (연결)<input type="number" value={newRow.revenue2025Consolidated||""} onChange={e=>setNewRow({...newRow,revenue2025Consolidated:Number(e.target.value)})}/></label><label>브랜드사<input value={newRow.brands} onChange={e=>setNewRow({...newRow,brands:e.target.value})}/></label><label>ODM사<input value={newRow.odm} onChange={e=>setNewRow({...newRow,odm:e.target.value})}/></label><label>해당품목<input value={newRow.items} onChange={e=>setNewRow({...newRow,items:e.target.value})}/></label><label>인수, 합병<input value={newRow.ma} onChange={e=>setNewRow({...newRow,ma:e.target.value})}/></label><div style={{gridColumn:"1 / -1",display:"flex",justifyContent:"flex-end",gap:7}}><button className="btn light" onClick={()=>setAddCategory(null)}>취소</button><button className="btn dark" onClick={addCompany}>기업 추가</button></div></div></div></div>}
 </main>;
}
