"use client";
import {useEffect,useMemo,useState} from "react";
import * as XLSX from "xlsx";
import {jsPDF} from "jspdf";
import {Bar,BarChart,CartesianGrid,Legend,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis,Cell} from "recharts";

type Basis="별도"|"연결"|"기업재무"|"미확인";
type Row={category:string;company:string;revenue2025:number;revenue2024:number;brands:string;overseas:string;business:string;employees:string;keyRoles:string;recruiterPoint:string;sourceStatus:string;note:string};

const seed:Row[]=[
{category:"대형 종합 뷰티",company:"LG생활건강",revenue2025:304073,revenue2024:353485,brands:"더후, CNP, 오휘",overseas:"북미·중국·일본",business:"화장품·생활용품·음료",employees:"최신 확인 필요",keyRoles:"글로벌영업, 브랜드마케팅, 상품기획, R&D",recruiterPoint:"글로벌 시장·브랜드 포트폴리오 재편에 대응할 인재",sourceStatus:"공시 별도매출",note:"2025/2024 별도매출"},
{category:"대형 종합 뷰티",company:"아모레퍼시픽",revenue2025:265372.6,revenue2024:241378.6,brands:"설화수, 라네즈, 헤라",overseas:"북미·일본·중국",business:"화장품·뷰티",employees:"최신 확인 필요",keyRoles:"글로벌영업, 브랜드마케팅, 상품기획, 디지털마케팅",recruiterPoint:"북미·일본 중심 글로벌 브랜드 확장 경험",sourceStatus:"공시 별도매출",note:"2025/2024 별도매출"},
{category:"성장 인디 브랜드",company:"에이피알",revenue2025:152829.6,revenue2024:72300.1,brands:"메디큐브, 에이프릴스킨, 포맨트",overseas:"미국·일본·중국 등",business:"뷰티 디바이스·화장품·패션",employees:"최신 확인 필요",keyRoles:"해외영업, 글로벌마케팅, 이커머스, 상품기획",recruiterPoint:"미주·일본·이커머스 성장에 대응할 글로벌 인재",sourceStatus:"공시 별도매출",note:"2025/2024 별도매출"},
{category:"성장 인디 브랜드",company:"구다이글로벌",revenue2025:4564.6334,revenue2024:3237.0118,brands:"조선미녀, 스킨1004, 티르티르, 스킨푸드",overseas:"북미·일본·유럽·동남아",business:"글로벌 뷰티 브랜드 빌더·유통·M&A",employees:"최신 확인 필요",keyRoles:"글로벌영업, 브랜드PM, M&A/PMI, 유통, 마케팅",recruiterPoint:"멀티브랜드 M&A와 글로벌 유통을 동시에 경험한 인재",sourceStatus:"2025/2024 별도매출",note:"2025 별도 4,564.6억원 / 2024 별도 3,237.0억원. 2025 연결은 1조4,718억원과 구분."},
{category:"성장 인디 브랜드",company:"브이티",revenue2025:38105,revenue2024:31930,brands:"VT, 리들샷",overseas:"일본·미국·유럽",business:"화장품·글로벌 뷰티",employees:"최신 확인 필요",keyRoles:"해외영업, 글로벌마케팅, 브랜드마케팅, 상품기획",recruiterPoint:"일본을 중심으로 한 글로벌 채널 확장 경험",sourceStatus:"공시 별도매출",note:"2025/2024 별도매출"},
{category:"성장 인디 브랜드",company:"달바글로벌",revenue2025:50259,revenue2024:30302,brands:"달바",overseas:"미국·일본·유럽",business:"프리미엄 뷰티 브랜드",employees:"최신 확인 필요",keyRoles:"글로벌영업, 브랜드마케팅, 이커머스, 상품기획",recruiterPoint:"프리미엄 브랜드의 해외 유통·D2C 확장 경험",sourceStatus:"공시 별도매출",note:"재무정보 기준 추가 교차검증 권장"},
{category:"성장 인디 브랜드",company:"더파운더즈",revenue2025:0,revenue2024:0,brands:"아누아",overseas:"북미·일본·160여개국",business:"글로벌 브랜드 빌더·화장품",employees:"327명(2025 공개자료)",keyRoles:"글로벌영업, 브랜드마케팅, 제품기획, SCM, 재무",recruiterPoint:"글로벌 사업 전 영역 인재 수요",sourceStatus:"연결매출만 확인",note:"2025 연결 7,177억원 / 2024 공개 매출 4,278억원. 별도매출 미확정."},
{category:"성장 인디 브랜드",company:"비나우",revenue2025:3165.79,revenue2024:2658.1041,brands:"넘버즈인, fwee, FLASKIN, RIAH",overseas:"미국·일본·대만 등 16개국",business:"멀티 뷰티 브랜드 운영",employees:"최신 확인 필요",keyRoles:"일본마케팅, 퍼포먼스마케팅, 해외영업, 상품디자인, 이커머스",recruiterPoint:"일본·미국·동남아 글로벌 확장과 멀티브랜드 운영 경험",sourceStatus:"NICE 기업재무 매출",note:"별도 여부는 공시 기준 추가 확인 필요"},
{category:"성장 인디 브랜드",company:"토리든",revenue2025:0,revenue2024:0,brands:"토리든",overseas:"미국·일본·유럽·41개국",business:"스킨케어 브랜드",employees:"219명(2026.05 공개자료)",keyRoles:"글로벌영업, 브랜드마케팅, 상품기획, 이커머스",recruiterPoint:"글로벌 리테일 확장과 스킨케어 전문성을 가진 인재",sourceStatus:"연결매출만 확인",note:"2025 연결 2,743억원 / 2024 매출 1,860억원. 별도매출 미확정."},
{category:"ODM",company:"코스맥스",revenue2025:152641.5,revenue2024:135766,brands:"글로벌 ODM",overseas:"미국·중국·동남아",business:"화장품 ODM",employees:"최신 확인 필요",keyRoles:"생산기획, 해외영업, R&D, 품질, SCM",recruiterPoint:"글로벌 ODM 고객 대응과 생산·품질·SCM 전문성",sourceStatus:"공시 별도매출",note:"2025/2024 별도매출"},
{category:"ODM",company:"한국콜마",revenue2025:119275.2,revenue2024:105966.9,brands:"글로벌 ODM",overseas:"미국·중국·북미",business:"화장품·건강기능식품 ODM",employees:"최신 확인 필요",keyRoles:"R&D, 생산, 품질, 해외영업, SCM",recruiterPoint:"글로벌 고객·공장 운영과 R&D/품질을 연결할 인재",sourceStatus:"공시 별도매출",note:"2025/2024 별도매출"},
{category:"플랫폼·유통",company:"올리브영",revenue2025:583350,revenue2024:478990,brands:"K-뷰티 유통 플랫폼",overseas:"글로벌 온라인·오프라인",business:"H&B 리테일·온라인 플랫폼",employees:"최신 확인 필요",keyRoles:"MD, 글로벌사업, 이커머스, 마케팅, 데이터",recruiterPoint:"K-뷰티 브랜드 발굴·글로벌 유통·이커머스 경험",sourceStatus:"공시/공개자료",note:"매출 기준은 공개 재무자료"}
];
const cats=["전체","대형 종합 뷰티","성장 인디 브랜드","ODM","플랫폼·유통"];
const chartColors=["#5B8DEF","#9B6BFF","#FF7A8A","#FFB454","#43C6A6","#5CC8E8","#F06FAE","#7E8CE0"];
const basis=(s:string):Basis=>s.includes("별도")?"별도":s.includes("연결")?"연결":s.includes("NICE")||s.includes("기업재무")?"기업재무":"미확인";
const badge=(b:Basis)=><span style={{display:"inline-block",padding:"4px 9px",borderRadius:999,fontSize:12,fontWeight:700,background:b==="별도"?"#e8f5e9":b==="연결"?"#fff4e5":b==="기업재무"?"#e8f0ff":"#f1f1f1",color:b==="별도"?"#16723a":b==="연결"?"#9a5b00":b==="기업재무"?"#2859a8":"#666"}}>{b}</span>;

export default function Home(){
 const[rows,setRows]=useState(seed),[filter,setFilter]=useState("전체"),[q,setQ]=useState(""),[selected,setSelected]=useState<Row|null>(null),[saved,setSaved]=useState(false);
 const[graphCompanies,setGraphCompanies]=useState<Row[]>([]),[dragging,setDragging]=useState<string|null>(null),[dragOver,setDragOver]=useState(false);
 useEffect(()=>{const x=localStorage.getItem("kbeauty-v7");if(x)try{setRows(JSON.parse(x))}catch{}},[]);
 const save=(x:Row[])=>{setRows(x);localStorage.setItem("kbeauty-v7",JSON.stringify(x));setSaved(true);setTimeout(()=>setSaved(false),1000)};
 const visible=useMemo(()=>rows.filter(r=>(filter==="전체"||r.category===filter)&&(!q||`${r.company} ${r.brands} ${r.overseas} ${r.business} ${r.keyRoles}`.toLowerCase().includes(q.toLowerCase()))),[rows,filter,q]);
 const growth=(r:Row)=>r.revenue2024?((r.revenue2025-r.revenue2024)/r.revenue2024*100):null;
 const comparable=rows.filter(r=>basis(r.sourceStatus)==="별도"&&r.revenue2024>0&&r.revenue2025>0);
 const ranked=[...comparable].sort((a,b)=>b.revenue2025-a.revenue2025),growthRank=[...comparable].sort((a,b)=>(growth(b)??-999)-(growth(a)??-999));
 const total25=comparable.reduce((s,r)=>s+r.revenue2025,0),total24=comparable.reduce((s,r)=>s+r.revenue2024,0);
 const counts={별도:rows.filter(r=>basis(r.sourceStatus)==="별도").length,연결:rows.filter(r=>basis(r.sourceStatus)==="연결").length,기업재무:rows.filter(r=>basis(r.sourceStatus)==="기업재무").length,미확인:rows.filter(r=>basis(r.sourceStatus)==="미확인").length};
 const chart=cats.slice(1).map(c=>({category:c,revenue:comparable.filter(r=>r.category===c).reduce((s,r)=>s+r.revenue2025,0)}));
 const compare=cats.slice(1).map(c=>({category:c,"2024":comparable.filter(r=>r.category===c).reduce((s,r)=>s+r.revenue2024,0),"2025":comparable.filter(r=>r.category===c).reduce((s,r)=>s+r.revenue2025,0)}));
 const graphData=graphCompanies.map(r=>({company:r.company,"2024":r.revenue2024,"2025":r.revenue2025,category:r.category}));
 const pieData=cats.slice(1).map(c=>({category:c,count:rows.filter(r=>r.category===c).length}));
 const addToGraph=(company:string)=>{const r=rows.find(x=>x.company===company);if(!r)return;setGraphCompanies(prev=>prev.some(x=>x.company===company)?prev:[...prev,r]);};
 const removeFromGraph=(company:string)=>setGraphCompanies(prev=>prev.filter(r=>r.company!==company));
 const reorderGraph=(target:string)=>{if(!dragging||dragging===target)return;setGraphCompanies(prev=>{const from=prev.findIndex(r=>r.company===dragging),to=prev.findIndex(r=>r.company===target);if(from<0||to<0)return prev;const next=[...prev];const[item]=next.splice(from,1);next.splice(to,0,item);return next})};
 const excel=()=>{const ws=XLSX.utils.json_to_sheet(rows.map(r=>({"산업군":r.category,"기업":r.company,"매출기준":basis(r.sourceStatus),"2025 매출(억원)":r.revenue2025||"확인 필요","2024 매출(억원)":r.revenue2024||"확인 필요","주요 브랜드":r.brands,"해외시장":r.overseas,"주요사업":r.business,"직원수":r.employees,"주요 채용직무":r.keyRoles,"헤드헌팅 포인트":r.recruiterPoint,"데이터 상태":r.sourceStatus,"메모":r.note})));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"K-뷰티 기업");XLSX.writeFile(wb,"2026-kbeauty-v7-data.xlsx")};
 const pdf=()=>{const d=new jsPDF();d.setFontSize(18);d.text("2026 K-Beauty Industry Map V7",15,18);let y=32;visible.forEach((r,i)=>{d.setFontSize(9);d.text(`${i+1}. ${r.company} | ${basis(r.sourceStatus)} | ${r.revenue2025?r.revenue2025.toLocaleString():"N/A"}억원`,15,y);y+=7;if(y>280){d.addPage();y=20}});d.save("2026-kbeauty-v7-report.pdf")};
 return <main className="page"><header className="hero"><div><div className="eyebrow">2026 K-BEAUTY INDUSTRY LANDSCAPE · V8</div><h1>한국 화장품 산업 지형도</h1><p>매출·브랜드·해외시장·채용수요를 연결하고, 기업을 드래그하면 그래프가 즉시 대응합니다.</p></div><div className="actions"><button className="btn light" onClick={excel}>엑셀 저장</button><button className="btn dark" onClick={pdf}>PDF 출력</button></div></header>
 <div className="notice">매출 TOP·성장률·산업군 비교는 <b>별도매출 확인 기업만</b> 계산합니다. 아래 인터랙티브 분석에서는 기업을 드래그해 원하는 기업만 비교할 수 있습니다.</div>
 <section className="cards"><div className="card"><span>등록 기업</span><b>{rows.length}</b></div><div className="card"><span>별도매출 2025 합계</span><b>{total25.toLocaleString()}<small> 억원</small></b></div><div className="card"><span>별도매출 2024 합계</span><b>{total24.toLocaleString()}<small> 억원</small></b></div><div className="card"><span>매출 기준</span><b>{counts.별도}<small> 별도</small></b></div></section>
 <section className="panel" style={{marginBottom:24}}><h2>매출 데이터 기준 현황</h2><div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:14}}>{(["별도","연결","기업재무","미확인"] as Basis[]).map(b=><div key={b} style={{display:"flex",gap:8,alignItems:"center",padding:"9px 12px",border:"1px solid #eee",borderRadius:12}}>{badge(b)}<strong>{counts[b]}개</strong></div>)}</div><p className="sub" style={{marginTop:12}}>기업별 상세 화면에서도 같은 기준 배지를 표시합니다.</p></section>
 <section className="charts"><div className="panel"><h2>산업군별 2025 별도매출</h2><p className="sub">컬러·마우스오버·클릭으로 상세 기업을 확인할 수 있습니다.</p><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart} margin={{top:10,right:10,left:5,bottom:10}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="category"/><YAxis/><Tooltip/><Bar dataKey="revenue" name="2025 별도매출(억원)" radius={[8,8,0,0]} isAnimationActive>{chart.map((_,i)=><Cell key={i} fill={chartColors[i]}/>)}</Bar></BarChart></ResponsiveContainer></div></div><div className="panel"><h2>산업 구조</h2><p className="sub">등록 기업 수 기준 · 마우스를 올려 비중 확인</p><div className="chart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={pieData} dataKey="count" nameKey="category" outerRadius={105} innerRadius={55} label isAnimationActive>{pieData.map((_,i)=><Cell key={i} fill={chartColors[i]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></div></div></section>
 <section className="analysis-grid"><div className="panel"><h2>2025 별도매출 TOP 5</h2><p className="sub">별도매출 기업만 비교</p><div className="ranklist">{ranked.slice(0,5).map((r,i)=><button className="rankrow" key={r.company} onClick={()=>setSelected(r)} draggable onDragStart={()=>setDragging(r.company)} onDragEnd={()=>setDragging(null)}><b>{i+1}</b><span>{r.company} {badge("별도")}</span><strong>{r.revenue2025.toLocaleString()}억</strong></button>)}</div></div><div className="panel"><h2>별도매출 성장률 TOP 5</h2><p className="sub">2024 → 2025</p><div className="ranklist">{growthRank.slice(0,5).map((r,i)=><button className="rankrow" key={r.company} onClick={()=>setSelected(r)} draggable onDragStart={()=>setDragging(r.company)} onDragEnd={()=>setDragging(null)}><b>{i+1}</b><span>{r.company} {badge("별도")}</span><strong>+{growth(r)!.toFixed(1)}%</strong></button>)}</div></div></section>
 <section className="panel"><h2>산업군별 2024 → 2025 별도매출</h2><p className="sub">두 연도의 변화를 한눈에 비교합니다.</p><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={compare} margin={{top:10,right:10,left:5,bottom:10}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="category"/><YAxis/><Tooltip/><Legend/><Bar dataKey="2024" name="2024" fill="#9AA7BD" radius={[7,7,0,0]} isAnimationActive/><Bar dataKey="2025" name="2025" fill="#5B8DEF" radius={[7,7,0,0]} isAnimationActive/></BarChart></ResponsiveContainer></div></section>
 <section className="panel graph-panel"><div className="toolbar"><div><h2>기업 드래그 → 인터랙티브 비교 그래프</h2><p className="sub">기업 행이나 기업명을 <b>마우스로 드래그해서 아래 그래프 영역에 놓으세요.</b> 놓은 기업의 2024·2025 매출이 자동으로 그래프와 상세 정보에 반영됩니다.</p></div><button className="btn light" onClick={()=>setGraphCompanies([])}>그래프 초기화</button></div>
 <div className={`dropzone ${dragOver?"dragover":""}`} onDragOver={e=>{e.preventDefault();setDragOver(true)}} onDragLeave={()=>setDragOver(false)} onDrop={e=>{e.preventDefault();setDragOver(false);const company=e.dataTransfer.getData("text/company")||dragging;if(company)addToGraph(company);setDragging(null)}}>
   <div className="drop-title">{graphCompanies.length?"기업이 연결된 비교 그래프":"여기에 기업을 놓으세요"}</div>
   <div className="graph-chips">{graphCompanies.map((r,i)=><div key={r.company} className="graph-chip" draggable onDragStart={()=>setDragging(r.company)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();reorderGraph(r.company)}}><span className="drag-handle">⠿</span><span>{r.company}</span><button onClick={e=>{e.stopPropagation();removeFromGraph(r.company)}}>×</button></div>)}</div>
   {graphCompanies.length?<div className="chart graph-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={graphData} margin={{top:18,right:15,left:5,bottom:10}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="company"/><YAxis/><Tooltip formatter={(value:number)=>`${Number(value).toLocaleString()}억원`}/><Legend/><Bar dataKey="2024" name="2024 매출" radius={[8,8,0,0]} isAnimationActive>{graphCompanies.map((_,i)=><Cell key={i} fill={chartColors[i%chartColors.length]}/>)}</Bar><Bar dataKey="2025" name="2025 매출" fill="#16233b" radius={[8,8,0,0]} isAnimationActive/></BarChart></ResponsiveContainer></div>:<div className="drop-hint">기업 데이터 아래에서 원하는 기업을 끌어다 놓으면<br/>기업별 2024·2025 매출 비교가 즉시 생성됩니다.</div>}
 </div>
 {graphCompanies.length>0&&<div className="graph-details">{graphCompanies.map((r,i)=><button key={r.company} className="graph-detail" onClick={()=>setSelected(r)}><span className="dot" style={{background:chartColors[i%chartColors.length]}}/><div><b>{r.company}</b><small>{r.category} · 2025 {r.revenue2025?r.revenue2025.toLocaleString():"확인 필요"}억원 · {basis(r.sourceStatus)}</small></div><strong>{growth(r)!==null?`${growth(r)!.toFixed(1)}%`:"-"}</strong></button>)}</div>}
 </section>
 <section className="panel"><div className="toolbar"><div><h2>기업 데이터</h2><p className="sub">기업명을 클릭하면 상세 분석을 보고, 기업 행을 드래그하면 위 비교 그래프로 보낼 수 있습니다.</p></div><div className="tools"><select value={filter} onChange={e=>setFilter(e.target.value)}>{cats.map(c=><option key={c}>{c}</option>)}</select><input placeholder="기업·브랜드·직무 검색" value={q} onChange={e=>setQ(e.target.value)}/></div></div><div className="tablewrap"><table><thead><tr><th>산업군</th><th>기업</th><th>매출 기준</th><th>2025</th><th>2024</th><th>증감률</th><th>주요 브랜드</th><th>해외시장</th></tr></thead><tbody>{visible.map((r,i)=><tr key={r.company} draggable onDragStart={e=>{e.dataTransfer.setData("text/company",r.company);e.dataTransfer.effectAllowed="copy";setDragging(r.company)}} onDragEnd={()=>setDragging(null)} className={dragging===r.company?"dragging-row":""}><td><span className="tag">{r.category}</span></td><td><button className="companybtn" draggable onDragStart={e=>{e.stopPropagation();e.dataTransfer.setData("text/company",r.company);setDragging(r.company)}} onClick={()=>setSelected(r)}><span className="grip">⋮⋮</span><b>{r.company}</b></button></td><td>{badge(basis(r.sourceStatus))}</td><td>{r.revenue2025?r.revenue2025.toLocaleString():"확인 필요"}</td><td>{r.revenue2024?r.revenue2024.toLocaleString():"확인 필요"}</td><td>{basis(r.sourceStatus)==="별도"&&growth(r)!==null?growth(r)!.toFixed(1)+"%":"-"}</td><td>{r.brands}</td><td>{r.overseas}</td></tr>)}</tbody></table></div>{saved&&<div className="saved">✓ 저장됨</div>}</section>
 {selected&&<div className="overlay" onClick={()=>setSelected(null)}><div className="detail" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><span className="tag">{selected.category}</span><h2>{selected.company}</h2><div style={{margin:"8px 0 18px"}}>{badge(basis(selected.sourceStatus))} <span style={{marginLeft:8,color:"#777",fontSize:13}}>매출 기준</span></div><div className="detailcards"><div><span>2025</span><b>{selected.revenue2025?selected.revenue2025.toLocaleString()+"억":"확인 필요"}</b></div><div><span>2024</span><b>{selected.revenue2024?selected.revenue2024.toLocaleString()+"억":"확인 필요"}</b></div><div><span>증감률</span><b>{basis(selected.sourceStatus)==="별도"&&growth(selected)!==null?growth(selected)!.toFixed(1)+"%":"-"}</b></div></div><dl><dt>주요사업</dt><dd>{selected.business||"미입력"}</dd><dt>주요 브랜드</dt><dd>{selected.brands||"미입력"}</dd><dt>해외시장</dt><dd>{selected.overseas||"미입력"}</dd><dt>주요 채용직무</dt><dd>{selected.keyRoles||"미입력"}</dd><dt>헤드헌팅 포인트</dt><dd>{selected.recruiterPoint||"미입력"}</dd><dt>직원수</dt><dd>{selected.employees||"최신 확인 필요"}</dd><dt>데이터 상태</dt><dd>{selected.sourceStatus}</dd><dt>메모</dt><dd>{selected.note||"-"}</dd></dl><button className="btn dark detail-add" onClick={()=>addToGraph(selected.company)}>이 기업을 비교 그래프에 추가</button></div></div>}
 <footer>2026 K-뷰티 산업 지형도 V8 · 컬러 인터랙티브 그래프 · 기업 드래그 분석 · Excel · PDF · GitHub · Vercel</footer></main>;
}
