"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import mammoth from "mammoth";
import * as pdfjsLib from "pdfjs-dist/legacy/build/pdf.mjs";
import { companies, sampleResume } from "../../lib/recruiting-data";

type AIItem = { company: string; score: number; verdict: string; why: string[]; strengths: string[]; gaps: string[]; role: string; market: string; recruiter_note: string };
type AIResult = { candidate_summary: string; recommended_role: string; recommended_market: string; top_recommendations: AIItem[]; resume_improvements: string[]; model?: string };
const STORAGE_KEY = "kbeauty_resume_profile";
const normalize = (value: string) => value.toLowerCase().replace(/[\s·,&/()\-]/g, "");
const has = (text: string, key: string) => normalize(text).includes(normalize(key));
function ruleScore(text: string, company: (typeof companies)[number]) { const role = company.roles.filter((item) => has(text, item)).length; const market = company.markets.filter((item) => has(text, item)).length; const keyword = company.keywords.filter((item) => has(text, item)).length; return Math.min(97, Math.max(15, 20 + role * 8 + market * 4 + keyword * 3)); }
async function extractDocx(file: File) { const result = await mammoth.extractRawText({ arrayBuffer: await file.arrayBuffer() }); return result.value.trim(); }
async function extractPdf(file: File) { const data = new Uint8Array(await file.arrayBuffer()); const pdf = await pdfjsLib.getDocument({ data }).promise; const pages: string[] = []; for (let pageNo = 1; pageNo <= pdf.numPages; pageNo += 1) { const page = await pdf.getPage(pageNo); const content = await page.getTextContent(); pages.push(content.items.map((item: any) => ("str" in item ? item.str : "")).join(" ")); } return pages.join("\n\n").trim(); }

export default function ResumeUpload() {
  const inputRef = useRef<HTMLInputElement>(null);
  const [text, setText] = useState(""); const [fileName, setFileName] = useState(""); const [busy, setBusy] = useState(false); const [aiBusy, setAiBusy] = useState(false); const [message, setMessage] = useState(""); const [ai, setAi] = useState<AIResult | null>(null);
  useEffect(() => { try { const saved = localStorage.getItem(STORAGE_KEY); if (!saved) return; const data = JSON.parse(saved); setText(data.resumeText || ""); setFileName(data.fileName || "최근 저장 이력서"); setAi(data.ai || null); } catch {} }, []);
  const ruleResults = useMemo(() => companies.map((company) => ({ company, score: ruleScore(text, company) })).sort((a, b) => b.score - a.score), [text]);
  async function handleFile(file: File) { setBusy(true); setMessage(""); setAi(null); setFileName(file.name); try { const name = file.name.toLowerCase(); let extracted = ""; if (name.endsWith(".txt") || name.endsWith(".md")) extracted = await file.text(); else if (name.endsWith(".docx")) extracted = await extractDocx(file); else if (name.endsWith(".pdf")) extracted = await extractPdf(file); else throw new Error("지원 형식: PDF, DOCX, TXT, MD"); setText(extracted); setMessage(`${file.name}을(를) 읽었습니다. 이제 AI 정밀 분석을 실행하세요.`); } catch (error) { setMessage(error instanceof Error ? error.message : "파일을 읽지 못했습니다."); } finally { setBusy(false); } }
  async function runAI() { if (!text.trim()) { setMessage("먼저 이력서를 선택하거나 내용을 붙여 넣으세요."); return; } setAiBusy(true); setMessage(""); try { const response = await fetch("/api/ai-match", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ resume: text, companies }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "AI 분석에 실패했습니다."); setAi(data); localStorage.setItem(STORAGE_KEY, JSON.stringify({ fileName, resumeText: text, ai: data, savedAt: new Date().toISOString() })); setMessage("AI 분석 결과를 저장했습니다. 후보자 관리와 AI 매칭에서 이어서 사용할 수 있습니다."); } catch (error) { setMessage(error instanceof Error ? error.message : "AI 분석 중 오류가 발생했습니다."); } finally { setAiBusy(false); } }
  function saveDraft() { localStorage.setItem(STORAGE_KEY, JSON.stringify({ fileName, resumeText: text, ai, savedAt: new Date().toISOString() })); setMessage("현재 이력서 분석 상태를 저장했습니다."); }
  function useSample() { setFileName("샘플 후보자"); setText(sampleResume); setAi(null); setMessage("샘플 이력서를 불러왔습니다."); }
  function reset() { setText(""); setFileName(""); setAi(null); setMessage(""); localStorage.removeItem(STORAGE_KEY); if (inputRef.current) inputRef.current.value = ""; }
  async function copy(value: string) { await navigator.clipboard?.writeText(value); setMessage("클립보드에 복사했습니다."); }

  return <main className="page">
    <header className="hero"><div><div className="eyebrow">RESUME MATCH · V15 AI</div><h1>이력서 → K-뷰티 기업·직무 AI 추천</h1><p>PDF·DOCX·TXT·MD 이력서를 읽고 기업·직무·시장 적합도와 고객사 제출용 추천문안을 생성합니다.</p></div></header>
    <section className="notice">관리자 로그인 상태에서만 사용할 수 있습니다. 이력서 원문은 브라우저에 저장할 수 있으며, AI 분석을 실행할 때 서버를 통해 OpenAI API로 전송됩니다.</section>
    <section className="panel"><h2>1. 이력서 입력</h2><p className="sub">파일을 선택하거나 내용을 직접 붙여 넣은 뒤 AI 정밀 분석을 실행하세요.</p><div className="addbox"><button className="btn dark" onClick={() => inputRef.current?.click()} disabled={busy}>{busy ? "파일 읽는 중..." : "이력서 파일 선택"}</button><input ref={inputRef} type="file" accept=".pdf,.docx,.txt,.md" style={{ display: "none" }} onChange={(e) => { const file = e.target.files?.[0]; if (file) void handleFile(file); }} /><button className="btn" onClick={useSample}>샘플 후보자 입력</button><button className="btn" onClick={saveDraft} disabled={!text}>현재 상태 저장</button><button className="btn" onClick={reset}>초기화</button></div>{fileName && <p className="sub">선택 파일: <b>{fileName}</b></p>}<textarea value={text} onChange={(e) => { setText(e.target.value); setAi(null); }} placeholder="이력서 내용을 붙여 넣어도 됩니다." style={{ width: "100%", minHeight: 260, marginTop: 12, padding: 16, border: "1px solid #d9e0ea", borderRadius: 12, fontSize: 14, lineHeight: 1.7, boxSizing: "border-box" }} /><div style={{ marginTop: 12, display: "flex", gap: 10, flexWrap: "wrap" }}><button className="btn dark" onClick={runAI} disabled={aiBusy || !text}>{aiBusy ? "AI 분석 중..." : "AI로 정밀 분석"}</button>{message && <span className="sub" style={{ alignSelf: "center" }}>{message}</span>}</div></section>
    <section className="panel"><h2>2. 빠른 규칙 기반 1차 매칭</h2><p className="sub">AI 실행 전에도 직무·시장·키워드 기준의 참고 점수를 확인할 수 있습니다.</p><div className="ranklist">{ruleResults.slice(0, 5).map((item) => <div className="rankrow" key={item.company.name}><b>{item.score}%</b><span><strong>{item.company.name}</strong> · {item.company.point}</span></div>)}</div></section>
    {ai && <><section className="panel"><div className="toolbar"><div><h2>3. AI 분석 결과</h2><p className="sub">모델: {ai.model || "OpenAI"}</p></div><button className="btn" onClick={() => copy(ai.candidate_summary)}>요약 복사</button></div><div className="cards"><div className="card"><span>추천 직무</span><b>{ai.recommended_role}</b></div><div className="card"><span>추천 시장</span><b>{ai.recommended_market}</b></div><div className="card"><span>추천 기업</span><b>{ai.top_recommendations?.length || 0}개</b></div><div className="card"><span>상태</span><b>저장됨</b></div></div><p style={{ whiteSpace: "pre-wrap", lineHeight: 1.8 }}>{ai.candidate_summary}</p></section><section className="panel"><h2>상위 기업 추천</h2><div className="candidategrid">{(ai.top_recommendations || []).map((item) => <article className="candidate" key={item.company}><div className="tag">{item.verdict}</div><h3>{item.company} · {item.score}%</h3><p><b>추천 직무:</b> {item.role} · <b>시장:</b> {item.market}</p><b>추천 근거</b>{item.why?.map((line) => <p key={line}>· {line}</p>)}<p><b>강점</b> · {item.strengths?.join(" · ")}</p><p className="muted"><b>보완/확인</b> · {item.gaps?.join(" · ") || "추가 확인사항 없음"}</p><button className="btn" onClick={() => copy(item.recruiter_note)}>고객사 추천문안 복사</button></article>)}</div></section><section className="panel"><h2>이력서 보완사항</h2><div className="ranklist">{(ai.resume_improvements || []).map((item, index) => <div className="rankrow" key={item}><b>{index + 1}</b><span>{item}</span></div>)}</div></section></>}
    <section className="panel"><h2>4. 헤드헌터 업무 활용</h2><ol><li>후보자 PDF/DOCX를 선택합니다.</li><li>AI 정밀 분석을 실행합니다.</li><li>상위 기업의 강점·부족점·추천 직무를 확인합니다.</li><li>고객사 제출용 추천문안을 복사합니다.</li><li>후보자 관리에서 DB 등록 후 AI 매칭에서 다시 분석할 수 있습니다.</li></ol></section><footer>V15 · 파일 업로드 · AI 정밀 분석 · 결과 저장 · 후보자 DB 연계 · AI 매칭 연계</footer>
  </main>;
}
