"use client";

import { useMemo, useState } from "react";
import mammoth from "mammoth";
import * as pdfjsLib from "pdfjs-dist/legacy/build/pdf.mjs";

type Company={name:string;category:string;roles:string[];markets:string[];keywords:string[];industry:string[];point:string};
type RuleResult={c:Company;score:number;matched:string[];missing:string[];role:string;market:string;breakdown:{industry:number;role:number;market:number;keyword:number;recency:number}};
type AIItem={company:string;score:number;verdict:string;why:string[];strengths:string[];gaps:string[];role:string;market:string;recruiter_note:string};
type AIResult={candidate_summary:string;recommended_role:string;recommended_market:string;top_recommendations:AIItem[];resume_improvements:string[];model?:string};

const companies:Company[]=[
["브이티","브랜드",["해외영업","글로벌마케팅","브랜드마케팅","상품기획"],["미국","유럽","일본"],["화장품","해외영업","수출","distributor","미국","유럽","일본","글로벌"],["화장품","뷰티","브랜드","글로벌"],"미주·유럽 해외영업과 글로벌 채널 확대 경험"],
["에이피알","브랜드·D2C",["해외영업","글로벌마케팅","이커머스","상품기획"],["미국","일본","중국"],["화장품","뷰티","해외영업","미국","일본","이커머스","D2C","글로벌"],["화장품","뷰티","이커머스","D2C"],"글로벌 D2C·이커머스와 미주·일본 경험"],
["달바글로벌","브랜드",["글로벌영업","브랜드마케팅","이커머스","MD"],["미국","유럽","일본"],["화장품","프리미엄","해외영업","미국","유럽","일본","이커머스","MD"],["화장품","뷰티","프리미엄","이커머스"],"프리미엄 뷰티 해외 유통·이커머스 경험"],
["구다이글로벌","멀티브랜드·유통",["글로벌영업","브랜드PM","유통","마케팅"],["북미","일본","유럽","동남아"],["화장품","글로벌","브랜드","유통","M&A","미국","일본","마케팅"],["화장품","뷰티","브랜드","유통"],"멀티브랜드·글로벌 유통과 시장 확장 경험"],
["더파운더즈","브랜드",["해외영업","글로벌마케팅","브랜드마케팅","MD"],["미국","일본","동남아","유럽"],["화장품","뷰티","해외영업","글로벌","브랜드","미국","일본","마케팅","MD"],["화장품","뷰티","브랜드"],"브랜드 성장과 해외 채널 확장 경험"],
["비나우","브랜드",["해외영업","글로벌마케팅","브랜드마케팅","상품기획"],["미국","일본","유럽"],["화장품","뷰티","해외영업","글로벌","브랜드","미국","일본","유럽"],["화장품","뷰티","브랜드"],"브랜드 기반 글로벌 영업·마케팅 경험"],
["토리든","브랜드",["해외영업","글로벌마케팅","MD","상품기획"],["미국","일본","유럽","동남아"],["화장품","스킨케어","해외영업","글로벌","미국","일본","유럽","MD"],["화장품","뷰티","스킨케어"],"스킨케어 해외영업과 글로벌 채널 경험"],
["아모레퍼시픽","종합 뷰티",["해외영업","글로벌마케팅","브랜드마케팅","상품기획","SCM"],["북미","미국","일본","중국","유럽"],["화장품","뷰티","해외영업","글로벌","브랜드","마케팅","SCM","미국","일본","중국"],["화장품","뷰티","브랜드","글로벌"],"대형 뷰티기업의 글로벌 브랜드·시장 운영 경험"],
["LG생활건강","종합 뷰티",["해외영업","글로벌마케팅","브랜드마케팅","상품기획","SCM"],["북미","미국","중국","일본","아시아"],["화장품","뷰티","해외영업","글로벌","브랜드","마케팅","SCM","미국","중국","일본"],["화장품","뷰티","브랜드","글로벌"],"글로벌 브랜드 운영과 대형 조직 경험"],
["코스맥스","ODM·제조",["해외영업","생산기획","R&D","품질","SCM"],["미국","중국","동남아","유럽"],["ODM","OEM","화장품","해외영업","SCM","생산","품질","R&D","미국","중국"],["화장품","ODM","OEM","제조"],"화장품 OEM/ODM·글로벌 고객 대응 경험"],
["한국콜마","ODM·제조",["해외영업","R&D","생산","품질","SCM"],["미국","중국","북미","유럽"],["ODM","OEM","화장품","해외영업","SCM","생산","품질","R&D","미국","중국"],["화장품","ODM","OEM","제조"],"화장품 ODM·R&D·품질·글로벌 고객 경험"],
["코스메카코리아","ODM·제조",["해외영업","생산","품질","R&D","SCM"],["미국","중국","유럽","동남아"],["ODM","OEM","화장품","해외영업","생산","품질","R&D","SCM","미국","유럽"],["화장품","ODM","OEM","제조"],"ODM 제조와 해외 고객·생산 대응 경험"],
["씨앤씨인터내셔널","ODM·색조",["해외영업","생산","R&D","품질","상품기획"],["미국","유럽","일본","아시아"],["ODM","화장품","색조","해외영업","생산","R&D","품질","미국","유럽","일본"],["화장품","ODM","색조","제조"],"색조 ODM과 글로벌 고객 대응 경험"],
["실리콘투","K-뷰티 유통",["해외영업","글로벌영업","유통","MD","이커머스"],["미국","유럽","아시아","중동"],["화장품","K-뷰티","해외영업","글로벌","유통","이커머스","미국","유럽","중동","MD"],["화장품","K-뷰티","유통","이커머스"],"K-뷰티 글로벌 유통·수출·이커머스 경험"],
["CJ올리브영","리테일·플랫폼",["글로벌사업","해외영업","MD","이커머스","상품기획"],["미국","일본","유럽","동남아"],["화장품","K-뷰티","글로벌","유통","이커머스","MD","상품기획","미국","일본"],["화장품","K-뷰티","유통","이커머스"],"K-뷰티 리테일·플랫폼과 글로벌 사업 경험"]
].map(([name,category,roles,markets,keywords,industry,point])=>({name,category,roles,markets,keywords,industry,point} as Company));

const sample=`[샘플 후보자]\n의료기기 해외영업 3년. 유럽·CIS·아시아·중동 15개국 담당, 바이어/디스트리뷰터 약 30개사 관리. LinkedIn으로 동남아 신규 디스트리뷰터 발굴. 최근 화장품 OEM/ODM 해외영업 경험. 미국 교육 및 체류 경험. 견적·수주·납기·샘플·규제·선적·통관 업무 수행.`;
const norm=(s:string)=>s.toLowerCase().replace(/[\s·,&/()\-]/g,"");
const has=(text:string,k:string)=>norm(text).includes(norm(k));
const unique=(a:string[])=>[...new Set(a)];
function analyze(text:string,c:Company):RuleResult{
 const kh=c.keywords.filter(k=>has(text,k)), ih=c.industry.filter(k=>has(text,k)), rh=c.roles.filter(k=>has(text,k)), mh=c.markets.filter(k=>has(text,k));
 const keyword=Math.min(30,Math.round(kh.length/c.keywords.length*30)); const industry=Math.min(25,ih.length*8); const role=Math.min(25,rh.length?9+rh.length*6:0); const market=Math.min(15,mh.length?6+mh.length*3:0); const recency=has(text,"최근")&&ih.length?5:0;
 const score=Math.max(15,Math.min(97,Math.round(keyword+industry+role+market+recency)));
 return {c,score,matched:unique([...ih,...rh,...mh,...kh]).slice(0,8),missing:unique([...c.industry,...c.roles,...c.markets]).filter(k=>!has(text,k)).slice(0,6),role:rh[0]||c.roles[0],market:mh[0]||c.markets[0],breakdown:{industry,role,market,keyword,recency}};
}
async function extractDocx(file:File){const r=await mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()});return r.value.trim();}
async function extractPdf(file:File){const data=new Uint8Array(await file.arrayBuffer());const pdf=await pdfjsLib.getDocument({data,disableWorker:true}).promise;const pages:string[]=[];for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i);const c=await p.getTextContent();pages.push(c.items.map((x:any)=>"str" in x?x.str:"").join(" "));}return pages.join("\n\n").trim();}

export default function ResumeUpload(){
 const[text,setText]=useState("");const[fileName,setFileName]=useState("");const[busy,setBusy]=useState(false);const[aiBusy,setAiBusy]=useState(false);const[notice,setNotice]=useState("");const[expanded,setExpanded]=useState<string|null>(null);const[category,setCategory]=useState("전체");const[ai,setAi]=useState<AIResult|null>(null);
 const results=useMemo(()=>companies.map(c=>analyze(text,c)).sort((a,b)=>b.score-a.score),[text]);const filtered=category==="전체"?results:results.filter(r=>r.c.category===category);const top=results[0];const categories=["전체",...unique(companies.map(c=>c.category))];
 const file=async(f:File)=>{setBusy(true);setFileName(f.name);setNotice("");setAi(null);try{const n=f.name.toLowerCase();if(n.endsWith(".txt")||n.endsWith(".md"))setText(await f.text());else if(n.endsWith(".docx"))setText(await extractDocx(f));else if(n.endsWith(".pdf"))setText(await extractPdf(f));else setNotice("지원 형식: PDF, DOCX, TXT, MD");}catch{setNotice("파일을 읽지 못했습니다. 이력서 내용을 붙여 넣어 주세요.");}finally{setBusy(false);}};
 const copy=(s:string)=>navigator.clipboard?.writeText(s);
 const runAI=async()=>{if(!text.trim())return;setAiBusy(true);setNotice("");try{const r=await fetch("/api/ai-match",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({resume:text,companies:companies.map(({name,category,roles,markets,point})=>({name,category,roles,markets,point}))})});const d=await r.json();if(!r.ok)throw new Error(d.error||"AI 분석 실패");setAi(d);}catch(e){setNotice(e instanceof Error?e.message:"AI 분석에 실패했습니다.");}finally{setAiBusy(false);}};
 const recruiterText=(r:RuleResult)=>`${r.c.name} 추천 후보자입니다. ${r.c.point}. ${r.role} 직무와 ${r.market} 시장 경험 측면에서 이력서와의 연결성이 높으며, 1차 적합도는 ${r.score}%입니다. 주요 매칭 역량은 ${r.matched.join(", ")}입니다. 다만 ${r.missing.join(", ")}은 실제 JD와 추가 확인이 필요합니다.`;
 const reportText=(r:RuleResult)=>`[${r.c.name}]\n적합도: ${r.score}%\n추천 직무: ${r.role}\n추천 시장: ${r.market}\n매칭 근거: ${r.matched.join(", ")}\n보완 확인: ${r.missing.join(", ")}\n점수 구성: 산업 ${r.breakdown.industry} / 직무 ${r.breakdown.role} / 시장 ${r.breakdown.market} / 키워드 ${r.breakdown.keyword} / 최근경력 ${r.breakdown.recency}`;
 return <main className="page"><header className="hero"><div><div className="eyebrow">RESUME MATCH · V14 AI</div><h1>이력서 → K-뷰티 기업·직무 AI 추천</h1><p>이력서의 경력 문맥을 AI로 분석해 기업·직무·시장 적합도와 고객사 제출용 추천문안까지 만듭니다.</p></div></header>
 <section className="panel"><h2>1. 이력서 입력</h2><p className="sub">PDF·DOCX·TXT·MD 파일을 브라우저에서 읽습니다. AI 분석을 누를 때만 이력서 텍스트가 AI API로 전송됩니다.</p><label className="btn dark">이력서 파일 선택<input hidden type="file" accept=".pdf,.docx,.txt,.md" onChange={e=>e.target.files?.[0]&&file(e.target.files[0])}/></label>{fileName&&<span className="file"> {fileName}</span>}{busy&&<p>파일을 읽고 있습니다...</p>}{notice&&<div className="notice">{notice}</div>}<textarea className="resume" value={text} onChange={e=>{setText(e.target.value);setAi(null)}} placeholder="이력서 내용을 붙여 넣거나 파일을 선택하세요."/><div className="actions"><button className="btn light" onClick={()=>{setText(sample);setAi(null)}}>샘플 후보자 입력</button><button className="btn dark" disabled={!text.trim()||aiBusy} onClick={runAI}>{aiBusy?"AI 분석 중...":"AI로 정밀 분석"}</button><button className="btn light" onClick={()=>{setText("");setFileName("");setNotice("");setAi(null);setExpanded(null)}}>초기화</button></div></section>
 {text&&<>
 <section className="panel"><h2>2. AI 헤드헌터 분석</h2>{ai?<><div className="summary"><div><span>추천 직무</span><strong>{ai.recommended_role}</strong></div><div><span>추천 시장</span><strong>{ai.recommended_market}</strong></div><div><span>AI 모델</span><strong>{ai.model||"GPT-5.6"}</strong></div></div><div className="detail"><b>후보자 포지셔닝</b><p>{ai.candidate_summary}</p><b>이력서 보완사항</b><p>{ai.resume_improvements.join(" · ")}</p></div><h3>AI 상위 추천</h3><div className="matchgrid">{ai.top_recommendations.map((r,i)=><article className="match" key={`${r.company}-${i}`}><div className="matchhead"><span className="rank">{i+1}</span><h3>{r.company}</h3><strong>{r.score}%</strong></div><p>{r.verdict}</p><dl><dt>추천 직무</dt><dd>{r.role}</dd><dt>추천 시장</dt><dd>{r.market}</dd><dt>핵심 근거</dt><dd>{r.why.join(" · ")}</dd><dt>강점</dt><dd>{r.strengths.join(" · ")}</dd><dt>보완·확인</dt><dd>{r.gaps.join(" · ")}</dd></dl><div className="detail"><b>고객사 제출용 추천문안</b><p>{r.recruiter_note}</p><button className="btn light" onClick={()=>copy(r.recruiter_note)}>추천문안 복사</button></div></article>)}</div></>:<div className="aiPrompt"><p>규칙 기반 결과보다 후보자의 경력 문맥을 깊게 분석하려면 AI 정밀 분석을 실행하세요.</p><button className="btn dark" disabled={aiBusy} onClick={runAI}>{aiBusy?"분석 중...":"AI 정밀 분석 시작"}</button></div>}</section>
 <section className="panel"><h2>3. 규칙 기반 전체 스크리닝</h2><div className="summary"><div><span>현재 1위</span><strong>{top.c.name}</strong><b>{top.score}%</b></div><div><span>추천 직무</span><strong>{top.role}</strong></div><div><span>추천 시장</span><strong>{top.market}</strong></div><div><span>등록 기업</span><strong>{companies.length}개</strong></div></div><div className="filters">{categories.map(x=><button key={x} className={category===x?"filter active":"filter"} onClick={()=>setCategory(x)}>{x}</button>)}</div><div className="matchgrid">{filtered.map((r,i)=><article className="match" key={r.c.name}><div className="matchhead"><span className="rank">{i+1}</span><h3>{r.c.name}</h3><strong>{r.score}%</strong></div><p>{r.score>=80?"강력 추천":r.score>=65?"검토 추천":r.score>=50?"조건부 검토":"적합도 낮음"}</p><dl><dt>추천 직무</dt><dd>{r.role}</dd><dt>추천 시장</dt><dd>{r.market}</dd><dt>핵심 매칭</dt><dd>{r.matched.length?r.matched.join(" · "):"뚜렷한 매칭 근거 부족"}</dd></dl><button className="link" onClick={()=>setExpanded(expanded===r.c.name?null:r.c.name)}>{expanded===r.c.name?"상세 닫기":"상세 분석"}</button>{expanded===r.c.name&&<div className="detail"><b>추천 사유</b><p>{r.c.point}</p><b>점수 구성</b><p>산업 {r.breakdown.industry} · 직무 {r.breakdown.role} · 시장 {r.breakdown.market} · 키워드 {r.breakdown.keyword} · 최근경력 {r.breakdown.recency}</p><b>보완 확인</b><p>{r.missing.join(" · ")||"추가 확인 필요 항목 없음"}</p><div className="actions"><button className="btn light" onClick={()=>copy(recruiterText(r))}>헤드헌터 추천문안 복사</button><button className="btn light" onClick={()=>copy(reportText(r))}>분석 결과 복사</button></div></div>}</article>)}</div></section></>}
 <section className="panel"><h2>4. 헤드헌터 업무 활용</h2><ol><li>후보자 PDF/DOCX를 선택합니다.</li><li>AI 정밀 분석을 실행합니다.</li><li>상위 기업의 강점·부족점·추천 직무를 확인합니다.</li><li>고객사 제출용 추천문안을 검토 후 복사합니다.</li><li>실제 JD와 후보자 경력을 최종 대조합니다.</li></ol></section><footer>2026 K-뷰티 산업 지형도 V14 AI · 등록 기업 15개 · 규칙 기반 + AI 정밀 매칭</footer></main>;
}
