"use client";
import {useMemo,useState} from "react";

type Company={name:string;roles:string[];markets:string[];keywords:string[];point:string};
const companies:Company[]=[
{name:"브이티",roles:["해외영업","글로벌마케팅","브랜드마케팅","상품기획"],markets:["미국","유럽","일본"],keywords:["화장품","해외영업","수출","distributor","미국","유럽","일본","글로벌"],point:"미주·유럽 해외영업과 글로벌 채널 확대 경험이 있는 후보자"},
{name:"에이피알",roles:["해외영업","글로벌마케팅","이커머스","상품기획"],markets:["미국","일본","중국"],keywords:["화장품","뷰티","해외영업","미국","일본","이커머스","D2C","글로벌"],point:"글로벌 D2C와 미주·일본 시장 경험이 강한 후보자"},
{name:"달바글로벌",roles:["글로벌영업","브랜드마케팅","이커머스","MD"],markets:["미국","유럽","일본"],keywords:["화장품","프리미엄","해외영업","미국","유럽","일본","이커머스","MD"],point:"프리미엄 뷰티의 해외 유통·D2C 경험이 있는 후보자"},
{name:"구다이글로벌",roles:["글로벌영업","브랜드PM","유통","마케팅"],markets:["북미","일본","유럽","동남아"],keywords:["화장품","글로벌","브랜드","유통","M&A","미국","일본","마케팅"],point:"멀티브랜드·글로벌 유통 경험이 있는 후보자"},
{name:"코스맥스",roles:["해외영업","생산기획","R&D","품질","SCM"],markets:["미국","중국","동남아"],keywords:["ODM","OEM","화장품","해외영업","SCM","생산","품질","R&D"],point:"화장품 OEM/ODM과 글로벌 고객 대응 경험이 있는 후보자"},
{name:"한국콜마",roles:["해외영업","R&D","생산","품질","SCM"],markets:["미국","중국","북미"],keywords:["ODM","OEM","화장품","해외영업","SCM","생산","품질","R&D"],point:"화장품 ODM·R&D·품질·글로벌 고객 경험이 있는 후보자"}
];
const sample=`[샘플 후보자]\n의료기기 해외영업 3년. 유럽·CIS·아시아·중동 15개국 담당, 바이어/디스트리뷰터 약 30개사 관리. LinkedIn으로 동남아 신규 디스트리뷰터 발굴. 최근 화장품 OEM/ODM 해외영업 경험. 미국 교육 및 체류 경험. 견적·수주·납기·샘플·규제·선적·통관 업무 수행.`;
function score(text:string,c:Company){const t=text.toLowerCase();let hit=0;c.keywords.forEach(k=>{if(t.includes(k.toLowerCase()))hit++});const role=c.roles.some(r=>t.includes(r.toLowerCase()))?12:0;const market=c.markets.some(m=>t.includes(m.toLowerCase()))?10:0;return Math.min(98,Math.round(40+hit/c.keywords.length*38+role+market));}
function extractDocx(file:File){return file.arrayBuffer().then(buf=>{const bytes=new Uint8Array(buf);const raw=new TextDecoder().decode(bytes);const texts=[...raw.matchAll(/<w:t[^>]*>([\s\S]*?)<\/w:t>/g)].map(m=>m[1]);return texts.join(" ").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">")})}
export default function ResumeUpload(){const[text,setText]=useState("");const[fileName,setFileName]=useState("");const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");const results=useMemo(()=>companies.map(c=>({c,s:score(text,c)})).sort((a,b)=>b.s-a.s),[text]);
 const file=async(f:File)=>{setBusy(true);setFileName(f.name);setNotice("");try{if(f.name.toLowerCase().endsWith(".txt")||f.name.toLowerCase().endsWith(".md")){setText(await f.text())}else if(f.name.toLowerCase().endsWith(".docx")){setText(await extractDocx(f))}else if(f.name.toLowerCase().endsWith(".pdf")){setNotice("PDF 파일은 브라우저 보안상 텍스트 추출을 자동화하지 않았습니다. 아래 입력창에 PDF 내용을 붙여 넣어 주세요.")}else{setNotice("지원 형식: PDF, DOCX, TXT, MD")} }catch{setNotice("파일 내용을 읽지 못했습니다. 이력서 내용을 입력창에 붙여 넣어 주세요.")}finally{setBusy(false)}};
 const copy=(s:string)=>navigator.clipboard?.writeText(s);
 return <main className="page"><header className="hero"><div><div className="eyebrow">RESUME MATCH · V11</div><h1>이력서 파일 → K-뷰티 기업 추천</h1><p>이력서 내용을 넣으면 현재 등록된 K-뷰티 기업의 직무·시장·핵심역량과 비교합니다.</p></div></header><section className="panel"><h2>1. 이력서 파일 업로드</h2><p className="sub">DOCX는 텍스트를 자동 추출합니다. PDF는 아래 입력창에 텍스트를 붙여 넣으면 분석할 수 있습니다.</p><label className="btn dark">파일 선택<input hidden type="file" accept=".pdf,.docx,.txt,.md" onChange={e=>e.target.files?.[0]&&file(e.target.files[0])}/></label>{fileName&&<span className="file"> {fileName}</span>}{busy&&<p>파일을 읽는 중입니다...</p>}{notice&&<div className="notice">{notice}</div>}<textarea className="resume" value={text} onChange={e=>setText(e.target.value)} placeholder="이력서 내용을 붙여 넣으세요."/><div className="actions"><button className="btn light" onClick={()=>setText(sample)}>샘플 후보자 입력</button><button className="btn dark" onClick={()=>setText("")}>초기화</button></div></section>{text&&<section className="panel"><h2>2. 기업 추천 결과</h2><p className="sub">규칙 기반 1차 매칭입니다. 실제 채용 의사결정 전에 원문 JD와 경력을 확인하세요.</p><div className="matchgrid">{results.map(({c,s},i)=><article className="match" key={c.name}><div className="matchhead"><span className="rank">{i+1}</span><h3>{c.name}</h3><strong>{s}%</strong></div><p>{s>=80?"강력 추천":s>=65?"검토 추천":"적합도 낮음"}</p><dl><dt>추천原因</dt><dd>{c.point}</dd><dt>매칭 직무</dt><dd>{c.roles.join(" · ")}</dd><dt>매칭 시장</dt><dd>{c.markets.join(" · ")}</dd></dl><button className="link" onClick={()=>copy(`${c.name} 추천 사유: ${c.point}\n추천 직무: ${c.roles.join(", ")}\n적합도: ${s}%`)}>추천 문안 복사</button></article>)}</div></section>}<section className="panel"><h2>3. 헤드헌터 활용법</h2><ol><li>PDF 이력서라면 내용을 복사해 입력창에 붙여 넣습니다.</li><li>추천 기업 순위를 확인합니다.</li><li>상위 기업의 실제 JD와 후보자 경력을 대조합니다.</li><li>추천 문안은 검토 후 고객사에 사용합니다.</li></ol></section><footer>2026 K-뷰티 산업 지형도 V11 · 이력서 매칭 · 개인정보는 브라우저에서만 처리</footer></main>}
