"use client";
import {useMemo,useState} from "react";

type Candidate={name:string;company:string;role:string;years:number;skills:string[];markets:string[];target:string;note:string};
const seed:Candidate[]=[
{name:"후보자 A",company:"의료기기/뷰티 OEM",role:"해외영업",years:3,skills:["B2B 해외영업","Distributor","LinkedIn lead generation","OEM/ODM"],markets:["미국","유럽","CIS","동남아","중동"],target:"브이티·에이피알·달바글로벌",note:"미주·유럽 해외영업 포지션에 특히 적합"},
{name:"후보자 B",company:"글로벌 소비재",role:"글로벌마케팅",years:7,skills:["브랜드마케팅","D2C","이커머스","퍼포먼스마케팅"],markets:["미국","일본"],target:"에이피알·아모레퍼시픽·달바글로벌",note:"글로벌 브랜드 확장 경험"},
{name:"후보자 C",company:"화장품 ODM",role:"생산기획/SCM",years:12,skills:["생산기획","SCM","SAP","품질","TPM"],markets:["한국","미국","중국"],target:"코스맥스·한국콜마",note:"ODM 생산본부 및 SCM 리더급 소싱 후보"}
];
const companies=[
["에이피알","글로벌영업, 글로벌마케팅, 이커머스, 상품기획","미국·일본·중국"],
["달바글로벌","글로벌영업, 브랜드마케팅, 이커머스, MD","미국·일본·유럽"],
["브이티","해외영업, 글로벌마케팅, 브랜드마케팅, 상품기획","일본·미국·유럽"],
["아모레퍼시픽","글로벌영업, 브랜드마케팅, 상품기획, 디지털마케팅","북미·일본·중국"],
["코스맥스","생산기획, 해외영업, R&D, 품질, SCM","미국·중국·동남아"],
["한국콜마","R&D, 생산, 품질, 해외영업, SCM","미국·중국·북미"]
];
function score(c:Candidate,co:string,roles:string,markets:string){const roleWords=roles.split(/[,·]/).map(x=>x.trim()).filter(Boolean);const marketWords=markets.split(/[·,]/).map(x=>x.trim());let s=45;s+=roleWords.some(x=>c.role.includes(x)||c.skills.some(k=>k.includes(x)||x.includes(k)))?30:0;s+=marketWords.some(x=>c.markets.includes(x))?15:0;s+=c.target.includes(co)?10:0;return Math.min(99,s)}
export default function Candidates(){const[cs,setCs]=useState(seed),[q,setQ]=useState(""),[company,setCompany]=useState("에이피알"),[newName,setNewName]=useState(""),[newRole,setNewRole]=useState(""),[newYears,setNewYears]=useState(0),[newSkills,setNewSkills]=useState("");const filtered=useMemo(()=>cs.filter(c=>!q||`${c.name} ${c.company} ${c.role} ${c.skills.join(" ")} ${c.markets.join(" ")}`.toLowerCase().includes(q.toLowerCase())),[cs,q]);const co=companies.find(x=>x[0]===company)??companies[0];const add=()=>{if(!newName.trim())return;setCs([...cs,{name:newName,company:"신규 입력",role:newRole||"미입력",years:newYears||0,skills:newSkills.split(",").map(x=>x.trim()).filter(Boolean),markets:[],target:"",note:"사용자 입력 후보자"}]);setNewName("");setNewRole("");setNewYears(0);setNewSkills("")};return <main className="page"><header className="hero"><div><div className="eyebrow">2026 K-BEAUTY · V9</div><h1>후보자 DB & 기업 매칭</h1><p>후보자의 경력·역량·시장 경험을 기업의 채용수요와 연결합니다.</p></div></header><section className="notice">개인정보 보호를 위해 실제 후보자 연락처·주민번호·주소 등 민감정보는 저장하지 않습니다. 이름도 내부 식별용으로 필요한 범위에서만 입력하세요.</section><section className="panel"><div className="toolbar"><div><h2>후보자 DB</h2><p className="sub">현재 샘플 3명 · 직접 후보자를 추가할 수 있습니다.</p></div><input placeholder="후보자·직무·역량 검색" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="addbox"><input placeholder="후보자명" value={newName} onChange={e=>setNewName(e.target.value)}/><input placeholder="현재 직무" value={newRole} onChange={e=>setNewRole(e.target.value)}/><input type="number" placeholder="경력" value={newYears||""} onChange={e=>setNewYears(Number(e.target.value))}/><input placeholder="핵심역량(쉼표 구분)" value={newSkills} onChange={e=>setNewSkills(e.target.value)}/><button className="btn dark" onClick={add}>후보자 추가</button></div><div className="candidategrid">{filtered.map(c=><article className="candidate" key={c.name}><div className="tag">{c.role}</div><h3>{c.name}</h3><p>{c.company} · 경력 {c.years}년</p><div className="chips">{c.skills.map(s=><span key={s}>{s}</span>)}</div><p className="muted">시장: {c.markets.join(" · ")||"미입력"}</p><b>추천 포인트</b><p>{c.note}</p></article>)}</div></section><section className="panel"><div className="toolbar"><div><h2>기업 ↔ 후보자 매칭</h2><p className="sub">현재 등록된 채용수요와 후보자의 경력·시장·직무를 기준으로 한 1차 적합도입니다.</p></div><select value={company} onChange={e=>setCompany(e.target.value)}>{companies.map(x=><option key={x[0]}>{x[0]}</option>)}</select></div><div className="matchhead"><b>{co[0]}</b><span>필요직무: {co[1]}</span><span>시장: {co[2]}</span></div><div className="matchlist">{filtered.map(c=><div className="matchrow" key={c.name}><div><b>{c.name}</b><span>{c.role} · {c.years}년</span></div><div className="meter"><i style={{width:`${score(c,co[0],co[1],co[2])}%`}}/></div><strong>{score(c,co[0],co[1],co[2])}%</strong><small>{score(c,co[0],co[1],co[2])>=80?"강력 추천":score(c,co[0],co[1],co[2])>=65?"검토 추천":"낮은 적합도"}</small></div>)}</div></section><footer>V9 · 후보자 DB · 기업↔후보자 매칭 · 개인정보 최소수집 원칙</footer></main>}
